### ISSUE TITLE
[BUG] Black mode for auto-dark mode doesn't work

### ISSUE THREAD

**Issue by ChAJ07** [Akylas/OSS-DocumentScanner#102]
### Version

App version: 1.3.2 Build 40
 

### What platform are you using?

Android

### OS Version

Oxygen OS 11/Android 11
Device - OP8

### What happened?

A bug happened!

It was expected to auto turn on black mode after turning on "Use black for auto-dark theme" 
This toggle automatically disabled after exiting the app.

https://github.com/Akylas/OSS-DocumentScanner/assets/101049867/ffbe0106-4ff9-4338-bd39-2b55bb197c18

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@ChAJ07 thanks for detailed report. I will fix it!

**Comment by farfromrefug** [comment]
@ChAJ07 should be fixed in latest version i just released

**Comment by ChAJ07** [comment]
Thank You that bug fixed but now(1) I'm unable to differentiate between Dark and Black. (2)Theme toggle doesn't change in real time after selecting another theme(You have to go to homepage then open settings to see changes)Third photo(device is in dark mode)
![Screenshot_20240131-090730](https://github.com/Akylas/OSS-DocumentScanner/assets/101049867/0d4da9c5-1979-47bc-91c4-c6658227d5c7)
![Screenshot_20240131-090744](https://github.com/Akylas/OSS-DocumentScanner/assets/101049867/64565dae-3738-418a-8798-7c05bf9cbfb5)
![Screenshot_20240131-091129](https://github.com/Akylas/OSS-DocumentScanner/assets/101049867/aadc99af-7d25-4be6-a190-7adcd4fcd6d6)

**Comment by farfromrefug** [comment]
@ChAJ07 sorry about that. should have tested everything

**Comment by farfromrefug** [comment]
@ChAJ07 please can you test latest version ?

**Comment by ChAJ07** [comment]
Thank You, Now It's fixed. Everything seems Ok.
