### ISSUE TITLE
[FR] Tap to focus & other improvements

### ISSUE THREAD

**Issue by Sureshgorai25** [Akylas/OSS-DocumentScanner#104]
Tap/Touch to focus on the specific part of the image/doc is very helpful in some cases. Hope you can implement it.

Another thing i noticed when you export a document in pdf the page of the document won't fill the entire page, it will some margin(Border) which doesn't looks good.
I hope you can add a option to disable that.
![Screenshot_20240131-073253](https://github.com/Akylas/OSS-DocumentScanner/assets/93507842/85b215db-f6e8-49fb-9c7d-e19949a89c50)

Also idk why but croping image is not that smooth, I can't crop it to the specific part I want. It works well in other scanners like CS, DS, etc.

Another feature i want to request is rename document while exporting or sharing And a setting to give the docs a name by default.
I love the app and i really appreciate your efforts.
Thanks

**Comment by farfromrefug** [comment]
@Sureshgorai25 happy to hear you like the app.
Many question there, let s try to handle them all

* Tap/Touch to focus on the specific part of the image/doc: dont understand what you mean. Are you talking about the camera or a document view? Can you please explain in details?
* export margin: you can change it using the chevron to shore more settings: either put the padding to 0 (if you want a4 pages) or use `full` mode for page layout (pdf page size will be the image size)
*  croping image is not that smooth: what do you mean by not smooth? can you share a video ?
* rename document: this is already possible. When exporting a pdf you will be asked for a name. You can also rename a document by clicking on the document name in the top action bar
* name by default: how would you expect that to work? you want some kind of a template name?

**Comment by Sureshgorai25** [comment]
• Yes, while capturing the document in viewfinder (Camera). Something like this
[https://drive.google.com/file/d/1wRXNOcmTtFU7NnmPFuDYdFMHprPoOICr/view?usp=drivesdk](url)

• I can't find that option. Setting like this will be helpful
![Screenshot_20240201-103051](https://github.com/Akylas/OSS-DocumentScanner/assets/93507842/5535b669-97e7-4030-aff6-754488c1d77a)

• About croping I'll send i video(Screen recording) later.

• Thanks for the info, i didn't know this was present.

• Yes template like this
![Screenshot_20240201-103132](https://github.com/Akylas/OSS-DocumentScanner/assets/93507842/c82eab08-7ac1-4861-b0a2-3456b41af39e)

**Comment by farfromrefug** [comment]
@Sureshgorai25 

* you can already tap to focus in the camera viewfinder. The only difference with your app is that there is no feedback right now.
* for padding setting (called padding in my app) it is there. I could make it in the app settings page. Not sure i want to yet. I would prefer not to have a multi page settings page if i can.
![Screenshot_1706781269](https://github.com/Akylas/OSS-DocumentScanner/assets/655344/4a9017e3-9811-4de8-9029-4111eb2b4760)
![Screenshot_1706781270](https://github.com/Akylas/OSS-DocumentScanner/assets/655344/82286c73-48e8-4f24-9109-d50fdf5552ca)
* name template. I will keep it as an idea. Wont add it today though. Could you open a feature request just for that please?

**Comment by farfromrefug** [comment]
@Sureshgorai25 can I close this issue. feels like everything is already implemented except for the new issue you vé created ?
