### ISSUE TITLE
[Please add a universal border or margin setting in the settings menu.]

### ISSUE THREAD

**Issue by code3AGL3** [Akylas/OSS-DocumentScanner#105]
The border setting shoul be such that top/bottom will have a control slider and left/right should have another slider.
And for the matter which one to choose during export should be the lesser one or have an extra border option in export menu for custom border for that perticular export.

**Comment by farfromrefug** [comment]
@code3AGL3 would you mind explaining this a bit more? Not even sure what border/margin you are talking about. Maybe with screenshots?

**Comment by farfromrefug** [comment]
@Aryan-Chauhan @juniorcaesar maybe one of you can explain the feature? i dont really understand

**Comment by Aryan-Chauhan** [comment]
Sir, I don't remember upvoting this issue.

It is requested to the author please explain the request in better words and with screenshots.

**Comment by code3AGL3** [comment]
I meant the padding on four sides of the page left should have a universal setting

**Comment by farfromrefug** [comment]
@code3AGL3 ok what padding are you talking about:
* pdf page export padding?
* document detection padding applied to "full rectangle" applied as corner when no document is detected?
* other?
*

**Comment by code3AGL3** [comment]
Sorry for this time waste i just found that you already added this setting to PDF export settings
