### ISSUE TITLE
Folder permissions on export do not persist

### ISSUE THREAD

**Issue by user8446** [Akylas/OSS-DocumentScanner#11]
Hi, this is a continuation from https://github.com/Akylas/com.akylas.documentscanner/issues/1

When exporting to a different folder from the last one that was exported to, I have to accept permissions for it again even though the folder has been used before.

Expected behavior:
Accepted folder permissions persist

I'm not an Android developer but I searched around and it seems with SAF you have to grant persistable permissions otherwise it asks again: https://stackoverflow.com/questions/32563428/storage-access-framework-persist-permissions-not-working

**Comment by farfromrefug** [comment]
@user8446 yes you are right and I already persist the permission .if I understand correctly the folder picker ask for your permission  even though you already did it once. if that is the case I think I can't do anything. 
the persistence happens when you export again to a folder you already picked (without picking again). like after an app restart

**Comment by user8446** [comment]
Hi it actually doesn't persist just changing folders with the app still open. You don't have to restart the app.

I'm not sure what the issue is either but I do know there are apps where it does persist. I'll check around to see if I can find something or hopefully someone knowledgeable on the issue can chime in.

**Comment by farfromrefug** [comment]
@user8446 I dont see any issue in what you are explaining. changing the export folder will always ask for permission. you need to explain what is the issue in the sense of what s not working in the app

**Comment by user8446** [comment]
Ok so every time the folder is changed for exporting, you have to go through the procedure to "use this folder", and then accept the permission:

![Screenshot_20231215-150047](https://github.com/Akylas/com.akylas.documentscanner/assets/18019245/7243689d-06cd-419c-9977-4d93cc2de9da)

---

![Screenshot_20231215-150421](https://github.com/Akylas/com.akylas.documentscanner/assets/18019245/5535de16-3965-4434-8fd8-cd2cbbc18739)

---

From what I have found, the app is what declares the persistence, when can even persist reboots: https://developer.android.com/training/data-storage/shared/documents-files#persist-permissions

Other apps after accepting the first time it doesn't ask again.

Sorry if this wasn't clear, please let me know how I can help test or further describe the issue.

**Comment by farfromrefug** [comment]
@user8446 give me an example app i can test that on. For me it seems normal, and as said persistent permission is working or you could not export a pdf after an app restart (without changing the export folder)

**Comment by user8446** [comment]
Hi, [GeniusScan](https://play.google.com/store/apps/details?id=com.thegrizzlylabs.geniusscan.free) , the PDF scanner app I would like to move from to a FOSS one - yours :)

After adding the folders for export one-time, the folder permission persists through both app restarts and device restarts.

**Comment by farfromrefug** [comment]
@user8446 I just tested with genius scan and it behaves to same way. every time I choose the export folder it asks for the permission again.
i am sorry but I dont see any issue here. your exports works as expected? even upon restart?

**Comment by user8446** [comment]
Just to be clear on GeniusScan after accepting folder permissions the first time that folder can be saved to indefinitely without any other interaction.

I am on a Pixel6a on Android 14 but it also worked this way on Android 13 & 10.

Hopefully some other users can try and test with their device as well.

**Comment by farfromrefug** [comment]
@user8446 i still dont understand what you explain. Yes on geniusScan it is saved in the app . It is the same in this app.|
please share a video showing the unwanted behavior

**Comment by user8446** [comment]
No problem, I will get a video shortly

**Comment by user8446** [comment]
Hi, sorry for the delay.  I hope this helps figure out how they did it.

I made 3 test folders with my file manager (Test, Test 2, & Test 3) and added all 3 for export in GeniusScan:


![Screenshot_20240101-181842](https://github.com/Akylas/com.akylas.documentscanner/assets/18019245/aedb6f77-92f1-4b43-abf1-d510dd3afbda)


I then exported a scan to each of the three folders in succession:


https://github.com/Akylas/com.akylas.documentscanner/assets/18019245/645a8be3-5eab-4639-9f89-f11560b2c7d4


Here is a screenshot of the history showing the scan exported to all three folders:


![Screenshot_20240101-182254](https://github.com/Akylas/com.akylas.documentscanner/assets/18019245/95110b43-bca8-43bc-b94f-b554f7f83381)


Here is something I noticed. Under "Storage & cache" for GeniusScan I show this:


![Screenshot_20240101-181436](https://github.com/Akylas/com.akylas.documentscanner/assets/18019245/6430d614-ce7f-4b69-8f66-79be4fe9554d)


Maybe that is a clue to how the folder permissions are persisting?

**Comment by farfromrefug** [comment]
@user8446 Thanks for the explanation of genius scan. Can you show a video of the behavior you get with my app which you dont think is correct?

**Comment by user8446** [comment]
Hi, here is a video showing exporting a PDF to 2 different folders. The additional security pop-up dialog shouldn't appear after granting access the first time. I have 26 different folders to export to depending on which one the PDF needs to go to.

Also you'll see a new error I haven't seen before where I had to try twice to change folders.

Security pop-up dialog:

![Screenshot 2024-01-07 085226](https://github.com/Akylas/com.akylas.documentscanner/assets/18019245/fdff7c6e-e7ed-4f83-9777-ee11c3c42f29)


https://github.com/Akylas/com.akylas.documentscanner/assets/18019245/5e749a18-14b3-4e45-bc10-be75a007c429

**Comment by user8446** [comment]
Hi, this was closed but the bug is still present. Was that a mistake?

**Comment by farfromrefug** [comment]
@user8446 if I look at the original issue reported here I dont sée any issue bût thé Android behavior. 
I am sorry asked you to detail.it more but even with that I did not see anything wrong and the app was behaving just like other apps you mentioned

**Comment by user8446** [comment]
Hi,

For some reason OSS Document scanner has this popup every single time a folder is changed whereas with Genius Scan the external storage permission is saved per the sceenshot above:

![294762781-fdff7c6e-e7ed-4f83-9777-ee11c3c42f29](https://github.com/Akylas/OSS-DocumentScanner/assets/18019245/8efac090-f3d9-44ec-abfe-bfbba4fccf27)

**Comment by farfromrefug** [comment]
@user8446 I just tested again with Genius Scan and it does exactly the same. Every time "a folder is changed" it asks exactly the same.
Plus there is no more external storage on latest android (where you see those allow dialogs).
We are doing the same and it is the expected behavior on all versions of android (which is different on <12 and >=12)
