### ISSUE TITLE
Error on startup: "invalid response 401: undefined"

### ISSUE THREAD

**Issue by OneCreek** [Akylas/OSS-DocumentScanner#110]
### Version

1.4.1 build 42

### What platform are you using?

Android

### OS Version

Android 14

### What happened?

When starting OSS freshly (force closed or regularly closed for some time) I get the message "invalid response 401: undefined" on startup (see screenshot).
![a6547b39-b5c6-4e92-8fd3-c6487e92d05e](https://github.com/Akylas/OSS-DocumentScanner/assets/107502675/ef036869-b3b5-4f00-8cd6-a4ede794a4cb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@OneCreek very strange issue as the app should notake any web request

could you try to reproduce with this build ? once you get the error please close / kill the app and restart it. I should receive a bug report
https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android

**Comment by OneCreek** [comment]
I can reproduce it. Also with your APK. Unfortunately, there is no bug report after force-closing and restarting...

**Comment by farfromrefug** [comment]
@OneCreek got it. you enabled WebDAV sync ?

**Comment by OneCreek** [comment]
Yes! And with the older version of OSS I had/have the issue https://github.com/Akylas/OSS-DocumentScanner/issues/99.
Don't know if it's related.

**Comment by farfromrefug** [comment]
OK I missed the fact it was the same related issue.
so in don't store your password and instead try to store a hash key . it works with nextcloud but does not seem to work with all WebDAV servers.
the tricky part is that i dont know what kind of security each server uses ans I dont know how to discover it yet.
I am sorry it is tricky and I dont have a solution yet

**Comment by OneCreek** [comment]
Ok thanks for the feedback. I didn't have the need for nextcloud yet and preferred the slimmer sftpgo. 
If I can help analyze or send new logs please let me know.

**Comment by farfromrefug** [comment]
closing as duplicate

**Comment by OneCreek** [comment]
I finally got it working! :) But too much changes on my and app side to reproduce I guess...
