### ISSUE TITLE
[BUG] crashing on lang selection

### ISSUE THREAD

**Issue by OshekharO** [Akylas/OSS-DocumentScanner#111]
### Version

Latest

### OS Version

Android 13

### What happened?

Crashing on language selection

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@OshekharO thanks for the report . could you reproduce it with this test build https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android?
that way I would get a bug report

**Comment by OshekharO** [comment]
> @OshekharO thanks for the report . could you reproduce it with this test build https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android? that way I would get a bug report

Same issue 😞

**Comment by OshekharO** [comment]
Also if possible can you add feature similar to other doc scanner in which we can scan multiple images and convert it into pdf directly without going back to home.

**Comment by farfromrefug** [comment]
@OshekharO sadly i did not get your bug report. Can you ensure you restart the app after the crash? i should get the report
As for your request you can already batch scan documents using the icon on the left of the capture button  (will make it more obvious)

**Comment by farfromrefug** [comment]
@OshekharO should be fixed in latest
