### ISSUE TITLE
[FEATURE REQUEST] Export to ODT

### ISSUE THREAD

**Issue by ConnorMeng** [Akylas/OSS-DocumentScanner#112]
PDFs can be difficult to use with other open source software, so it would be nice to have. Sorry for the short description but I can't think of much else to add.

**Comment by farfromrefug** [comment]
@ConnorMeng i understand your issue but there is no easy ODT lib to do the job. Seeing this is not requested a lot yet i will close this as not planned for now. If more people asks for this we can think of reopening it
