### ISSUE TITLE
[BUG] Page index shows only 1st digit

### ISSUE THREAD

**Issue by S-Joao-V** [Akylas/OSS-DocumentScanner#113]
### Version

v1.4.2 Build 43

### What platform are you using?

Android

### OS Version

Base Samsung S23 - Android 14 - One UI 6.0

### What happened?

After capturing multiple pages with the batch capture function (25+), edit some pictures in the preview page (with 50+ items), in my case apply a grayscale filter onto multiple pages while swiping through the pages.
After returning to the preview page I noticed that for some of the edited images, the page index would only show the first digit (1x,1x;4x,4x): 
![index](https://github.com/Akylas/OSS-DocumentScanner/assets/30469363/2c8208af-0f15-48ab-878e-823152a68276)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@S-Joao-V thanks for the report! you added the blue thing on the screenshot right?
Will fix it thanks!

**Comment by S-Joao-V** [comment]
@farfromrefug  correct!

**Comment by S-Joao-V** [comment]
@farfromrefug I could not see it anymore too. Tks!
