### ISSUE TITLE
[BUG] Empty thumbnail after editing image

### ISSUE THREAD

**Issue by S-Joao-V** [Akylas/OSS-DocumentScanner#114]
### Version

v1.4.2 Build 43

### What platform are you using?

Android

### OS Version

Base Samsung S23 - Android 14 - One UI 6.0

### What happened?

After capturing multiple pages with the batch capture function (25+), edit some pictures in the preview page (with 50+ items), in my case apply a grayscale filter onto multiple pages while swiping through the pages.
After returning to the preview page I noticed that for some of the edited images, the thumbnail does not show up:
![thumb](https://github.com/Akylas/OSS-DocumentScanner/assets/30469363/a6f0101c-7e7d-4e61-a79b-db3d50baaabb)

The empty thumbnails remained like that after:
-Exporting to pdf
-Previewing the pdf and returning to the list
Thumbnails showed after:
-Removing the app from the recent apps list and reopening the preview

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@S-Joao-V does it shows again if you close and open the app again?

**Comment by S-Joao-V** [comment]
@farfromrefug yes, with the step mentioned, locking/unlocking while in the page list had no effect.

**Comment by farfromrefug** [comment]
@S-Joao-V thanks i ll try to reproduce

**Comment by farfromrefug** [comment]
@S-Joao-V should be fixed in latest

**Comment by farfromrefug** [comment]
@S-Joao-V  i ll close this as done. Dont hesitate to open if not good for you
