### ISSUE TITLE
[FEATURE REQUEST] Feedback for batch adding captured pictures

### ISSUE THREAD

**Issue by S-Joao-V** [Akylas/OSS-DocumentScanner#115]
**Is your feature request related to a problem? Please describe.**
When you capture multiple pictures via the batch capture mode, after tapping the "v" icon there's a brief highlight but no other feedback, then adding large numbers of images (20+ ), the viewfinder remained active and the "v" icon could be tapped again.

**Describe the solution you'd like**
The viewfinder to go inactive, with a progress pop-up showing something is happening.
That the "v" icon to add the images should not be double-tappable.

**Comment by farfromrefug** [comment]
@S-Joao-V should be fixed in latest

**Comment by farfromrefug** [comment]
@S-Joao-V  i ll close this as done. Dont hesitate to open if not good for you

**Comment by S-Joao-V** [comment]
Hi @farfromrefug 
I checked with v1.4.6 Build 47, I think you added feedback on the capture action, not on the 'add' action, when taking a picture in bath mode I see the "capturing" then the "computing" messages, is that a recent addition?

My request for feedback was after the "V" icon is selected, with v1.4.6 Build 47, after capturing 10+ images the viewfinder is still active like in the initial comment, freezing the interactions with "computing" message would be nice.

**Comment by S-Joao-V** [comment]
Oh @farfromrefug , and i cant re-open the issue from my side.
