### ISSUE TITLE
[BUG] Error when exporting to PDF

### ISSUE THREAD

**Issue by jmzama** [Akylas/OSS-DocumentScanner#116]
### Version

1.4.2 Build 43

### What platform are you using?

Android

### OS Version

eOS v1.19

### What happened?

The following error arises when exporting to PDF. Nevertheless, the PDF is generated although it's a huge file (~45MB) compared with the JPG version (~4MB).
![IMG_20240205_194155](https://github.com/Akylas/OSS-DocumentScanner/assets/7407497/e84a2d80-506c-4e27-9f07-a5194dae4050)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmzama** [comment]
Yes, I think it is reproducible. My phone's specs can be found [here.](https://murena.com/shop/smartphones/brand-new/murena-one/#tech-spec)

**Comment by farfromrefug** [comment]
@jmzama just publised 1.4.3. If you could try with it and tell me if you still get the error
