### ISSUE TITLE
When manually cropping magnifier is hidden under finger

### ISSUE THREAD

**Issue by hexman1999** [Akylas/OSS-DocumentScanner#119]
### Version

1.4.3

### What platform are you using?

Android

### OS Version

Android 13

### What happened?

The magnifier of the manual crop should be shifted a little bit in order to see it, because it is hidden under my finger and can't see it clearly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@hexman1999 there should be a text in the view now explaining you how it works. The best way to use that feature is not to click on the corner itself but anywhere near it. I will find the closest one to your finger.
That way the magnifier is always at the expected place

**Comment by hexman1999** [comment]
> @hexman1999 there should be a text in the view now explaining you how it works. The best way to use that feature is not to click on the corner itself but anywhere near it. I will find the closest one to your finger.
> That way the magnifier is always at the expected place 

OK!, thanks, great work

**Comment by 48-mq** [comment]
@farfromrefug I ran into this same issue, and had to figure it out on my own (there was no explainer text). Also, I found the magnifier extremely difficult to use because of its high sensitivity. I also found it to be way too sensitive to the touch, which I will create a separate issue for right now.

**Comment by farfromrefug** [comment]
@48-mq there should be a text now to explain it. As for the sensitivity, maybe a video would help understand it? Like you feel the magnifier is moving too fast compare to your finger touch speed ? (I could make that a setting, here it feels OK)
