### ISSUE TITLE
[FEATURE REQUEST] Adding save to picture and individual save to pdf

### ISSUE THREAD

**Issue by hexman1999** [Akylas/OSS-DocumentScanner#120]
I think adding option to save individual pages as pdf will be better than always saving the whole set

And I wish if there is an option to export to a picture

Thanks

**Comment by farfromrefug** [comment]
@hexman1999 Exporting picture is already available but it was not clear. In the next version you'll see "share images"  which allow you to share or export images
as for exporting individual pages as PDF, great idea! in the next version when you select pages only those will be exported

**Comment by farfromrefug** [comment]
@hexman1999 can you confirm it works in latest?
