### ISSUE TITLE
[FEATURE REQUEST] enhanced PDF export

### ISSUE THREAD

**Issue by steadfasterX** [Akylas/OSS-DocumentScanner#123]
**Is your feature request related to a problem? Please describe.**

Problem: downscaling when exporting to pdf.

**Describe the solution you'd like**

Ideally one could change how the pdf export is done like scaling and ofc corner ranges. I usually expect that the full page is used for the scan but maybe others dont like that so an option for customizing that would be great.

**Describe alternatives you've considered**

The app "Docus" (also avail on fdroid) is doing that by default

**Comment by farfromrefug** [comment]
@steadfasterX sorry I am not sure I understand it all. maybe my PDF knowledge is not enough. would you mid detailing a bit?

you talk about full size image use in export. Did you sée the preview feature when you can change page size and margin?
maybe I need to have those settings added to the settings page

**Comment by steadfasterX** [comment]
@farfromrefug thx for the quick reply! I attach an example pdf which is not containing the scan full sized.

My workflow is pressing the pdf button -> export. I didnt even realized that preview button lol. 

Ok I will check if that will fix it for me thanks 😎👍 btw awesome project and support!

![Screenshot_20240210-112823_Adobe Acrobat__01.png](https://github.com/Akylas/OSS-DocumentScanner/assets/8750713/20cb4540-e5f9-4da9-8e42-f3d8d8cb36e8)

**Comment by farfromrefug** [comment]
@steadfasterX what s that app?

**Comment by steadfasterX** [comment]
You mean the pdf viewer? Adobe acrobat: https://play.google.com/store/apps/details?id=com.adobe.reader . Looks the same with the app xodo.

**Comment by farfromrefug** [comment]
@steadfasterX ok thanks. BTW i looked at docus and we use the same lib to create the PDF. So we should get the same compression

**Comment by steadfasterX** [comment]
Not sure if that is a compression issue.. seems like when doing the export it does not scale 100%

**Comment by farfromrefug** [comment]
@steadfasterX It might be related to the page size setting. If you choose "full" each pdf page size will be the size of the image.
If you select a4 or a3 then each pdf file will have that format. Then i draw the image in it with the defined margin

**Comment by steadfasterX** [comment]
@farfromrefug aah ok so : when I use the preview button and select "Full" here it has the expected result. the good thing is that it seems to save this setting so next time when I just choose pdf and then "export" instead of preview the result is still fine (full). maybe that is not very intuitive but well it works :)

**Comment by farfromrefug** [comment]
@steadfasterX yes i want to make it better. and i will change the default to full. Seems like it is what most people want

**Comment by farfromrefug** [comment]
@steadfasterX full is now the default. Will close this. IF you still have an issue dont hesitate to open again

**Comment by steadfasterX** [comment]
awesome! Many thx :)
