### ISSUE TITLE
[BUG] Auto Language got no default

### ISSUE THREAD

**Issue by cd-FileX** [Akylas/OSS-DocumentScanner#125]
### Version

1.4.4.45

### What platform are you using?

Android

### OS Version

Android 10

### What happened?

It seems like there is no fallback when the system language is not available, resulting in the translation storage values.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@cd-FileX You are saying if your device language is not one of the supported ones by the app, once you open the app for the first app nothing is translated?
it should default to english. Will check that.
Thanks!

**Comment by farfromrefug** [comment]
@cd-FileX thanks a lot. I fixed it and it will in the next version

**Comment by farfromrefug** [comment]
@cd-FileX now released let me know if it is fixed
