### ISSUE TITLE
[FEATURE REQUEST] use device camera app

### ISSUE THREAD

**Issue by hexman1999** [Akylas/OSS-DocumentScanner#126]
I wish if there is an option to use the native camera app as it has better interaction with camera and therefore clearer picture

**Comment by farfromrefug** [comment]
@hexman1999 will look into making that an option

**Comment by farfromrefug** [comment]
@hexman1999 implemented in latest version

**Comment by hexman1999** [comment]
Sounds great!

**Comment by hexman1999** [comment]
I think you can make batch option work by re-requesting cam app again and again after each scan until user close signal is sent (or closed without providing image)

**Comment by farfromrefug** [comment]
@hexman1999 yes but would require different UI which I am real sure about right now. so for now it will stay single
