### ISSUE TITLE
Not able to carry out continuous scan for more than one image

### ISSUE THREAD

**Issue by kar7hik** [Akylas/OSS-DocumentScanner#128]
### Version

v1.4.5 Build 46

### What platform are you using?

Android

### OS Version

Android 11

### What happened?

I am able to scan the first image. However, after it finishes the cropping of the first image, the camera crashes and goes to the app's home page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@kar7hik sorry to hear that. Could you try to reproduce the issue with this build https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android ? With this build i would receive a crash report. Dont forget to restart the app after the crash, this is when the report will be sent

**Comment by kar7hik** [comment]
As you mentioned, I have installed the app from the link and scanned the documents.

**Comment by farfromrefug** [comment]
@kar7hik thanks for testing it. Did it crash with the test build? Did you restart the app after the crash? Sadly i did not receive any log

**Comment by kar7hik** [comment]
It did crash with the test build. And I did restart the app after the crash. Let me check that again. I hope that you receive the log. Thank you for the wonderful piece of software.

**Comment by farfromrefug** [comment]
@kar7hik ok it is not what i thought it was then! Is auto scan enabled?  auto scan means if you stay on a document with the camera you get an animation and the document is automatically scanned  (goes to cropping page).

**Comment by farfromrefug** [comment]
@kar7hik by any chance could you make a video of the issue? Would help me a ton in reproducing it and fixing this for you!

**Comment by kar7hik** [comment]
@farfromrefug Sure. I'll add a screen recording. 

https://github.com/Akylas/OSS-DocumentScanner/assets/16447054/03688bf8-61ca-46e7-8785-74c187d7553a

**Comment by farfromrefug** [comment]
@kar7hik Thanks the video helps a lot! 
ONe question about the video. You are using auto scan, when the camera opens we then see the dialog with "capturing". Did you trigger that with the capture button yourself ?
* If so then everything we see is normal. You are not in batch mode (icon on the bottom left of the camera view). So when one image is capture the apps closes the camera view and shows the generated document as shown in your video
* If you did not click the capture button then this is the issue. YOu are in auto scan (capture button animating) (you can disable it from the settings as you shown or with a long press on the capture button), and your camera view does not seem to show that the camera did discover a document so the capture should not trigger automatically

**Comment by kar7hik** [comment]
@farfromrefug I did capture the image myself by pressing the capture button since the camera was not detecting the document. 

I didn't see the batch mode selection icon at the bottom left. I thought it was enabled by default hence I created an issue here. As you mentioned, it is working fine then. Excuse my ignorance. 

Thank you for your assistance. 😊

**Comment by farfromrefug** [comment]
@kar7hik no problem at all. Glad we understood it. And btw still means there is an issue in a sense that is not clear to users what should happen and why it is closing right after the first image
