### ISSUE TITLE
[BUG] Image too big in the menu after capturing

### ISSUE THREAD

**Issue by GaucovyAero** [Akylas/OSS-DocumentScanner#130]
### Version

v1.4.5 build 46

### What platform are you using?

Android

### OS Version

MIUI 14, Android 13

### What happened?

The captured image went over the text just after capturing and editing, if i click on the image again and go back, it goes back to normal.

https://github.com/Akylas/OSS-DocumentScanner/assets/85581164/5107630f-40b1-4b59-9dff-8d7bd2a87d37

### Relevant log output

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@GaucovyAero thanks i saw that too in development. Thought it was just a dev thing. But clearly wasnt :D Will try to fix that. Sorry about that

**Comment by GaucovyAero** [comment]
👍

**Comment by farfromrefug** [comment]
@GaucovyAero should be fixed in 1.4.6

**Comment by GaucovyAero** [comment]
> @GaucovyAero should be fixed in 1.4.6

fixed, thanks!
