### ISSUE TITLE
Configurable Export Folder

### ISSUE THREAD

**Issue by jotoeri** [Akylas/OSS-DocumentScanner#132]
**Is your feature request related to a problem? Please describe.**
Scanning a document to have it usable on any computer (or just a data archive storage) is quite a many-step thing. As such, i was quite happy to see the sync feature until i realised it does not sync the pdf-exports, but the whole - and only - the picture contents.

**Describe the solution you'd like**
Either having the possiblity to sync (particulary) the exported pdf-files via webdav or being able to configure an exclusive folder for exported pdfs (which i can automatically sync otherwise then).

**Comment by farfromrefug** [comment]
@jotoeri Yes the sync is only for the app "data". Now it was never the goal of the app to maintain a PDF library. Moreover when you scan a document, no PDF is generated at that point. It only happens once you specifically ask for it.
There are many reason for that (computing time, space usage ....)
I am really ok trying to find ways to make your workflow easier but we need to think this through and find the best solution while ensuring the app remains as fast and responsive as possible.
NOTE: the pdf generation is done on a background thread, so we could have a "sync pdf" process which automatically generates a pdf for documents once your create it. But it raises many questions like pdf name, what to do when you like add/remove a page to a pdf ...
If you are ok let s discuss it here and try to find the best solution

**Comment by jotoeri** [comment]
Yeah, fine by me to discuss! :)

It's an interesting point about the use-cases: For me, my mobile with this app is a pure scanning device to create pdf files. Everything else is how i use the documents then.
-> I'm curious for other use-cases! :)

So i totally agree, that this app doesnt have to maintain a pdf-library. I just have to bring the pdf-files to a place, where i can access the files and my library for sorting (i.e. my computer). So an automated cloud-storage inbetween would strongly ease at least my workflow.

For the pdf-creation, imo a manual trigger is fine, especially as - as you said - you have to set the filename, maybe edit the cropping before, maybe sort pages,... Just having the option, "once i hit the create button, the pdf appears on my computer" is the ideal goal for me. ;)

On the other hand - to have it mentioned and to think about - to have the original images on my cloud is **for my use-case** not at all necessary and thus a pure overhead. But as i said, i'm curious for other usages. :)

Cheers!
Jonas

**Comment by jotoeri** [comment]
Yes, thats fine, that was also my second suggestion on the first post. I hadn't found the export-folder setting in the global settings so i thought its not configurable. Now i got it.
From my side we could close this issue...

**Comment by farfromrefug** [comment]
@jotoeri you are right the setting is not easy to find. Will add it to global settings

**Comment by farfromrefug** [comment]
@jotoeri the setting is now added with all other settings in the app settings
