### ISSUE TITLE
Problem exporting the PDF because the modified images are not being integrated into the PDF.

### ISSUE THREAD

**Issue by franco27** [Akylas/OSS-DocumentScanner#135]
Version 1.4.6.47

Here is my smartphone system configuration:
Xiaomi Redmi 8
Android Version 10 Android 10
MIUI V12.5.2.0.QCNEUXM

Architecture 64-bit

Instruction sets
arm64-v8a armeabi-v7a armeabi Qualcomm® Snapdragon™ 439

CPU 4 x Cortex-A53
Cores 8
RAM size 4 GB

After adding photos from the gallery and modifying them with a filter, I wanted to get black text on a white background for printing.

Here are screenshots of the result.

![Screenshot_2024-02-17-09-34-19-563_com.akylas.documentscanner.jpg](https://github.com/Akylas/OSS-DocumentScanner/assets/31793920/fe804d92-e50b-490a-b9c8-1c096ac0c53b)

![Screenshot_2024-02-17-09-36-05-199_com.akylas.documentscanner.jpg](https://github.com/Akylas/OSS-DocumentScanner/assets/31793920/ac67f72a-ad1d-425e-96c3-42f386253037)

When I tried to export to PDF, my modifications to my photos or images were ignored. The changes were not retained when exporting to PDF, and another filter was applied. I wanted to keep black text on a white background.

![Screenshot_2024-02-17-09-34-49-067_com.akylas.documentscanner.jpg](https://github.com/Akylas/OSS-DocumentScanner/assets/31793920/bde6b9b7-6d87-4062-a571-a0dc5f298f25)

![Screenshot_2024-02-17-09-34-40-999_com.akylas.documentscanner.jpg](https://github.com/Akylas/OSS-DocumentScanner/assets/31793920/038fc1e0-be64-413a-9280-aafcab13876f)

It's unfortunate that there isn't an option to enhance black text, or intensify the black color of weak black text when it is grayed out.

**Comment by franco27** [comment]
I would like to congratulate the developers or developer for this very useful application. Great work has already been done.

**Comment by farfromrefug** [comment]
@franco27 thanks a lot for the kind words and the detailed explanation. really helps a lot.
I tried to reproduce your issue on android 10 and sadly could not do it.|
if this is reproducible (changing the color filter and then having export preview not apply it), could you make a video of it ? That could help me reproduce it

**Comment by franco27** [comment]
I am combining several videos to help you understand the issue.

I did not choose the color filter.

https://drive.google.com/file/d/1KF3DzXVs1JBA0PGtJfrV6bAuI3cqMUbS/view?usp=drivesdk

https://drive.google.com/file/d/1K6W3wO2dWH1URp9whs3aQbOad6Cz0CWG/view?usp=drivesdk

**Comment by franco27** [comment]
I am sending you the image that was used to create the three images.

To create the three images, I used only one image. I added three frames on this same photo. Then, I selected the Bw filter. In the "magic wand" tool, I did not activate anything.

When I made the two videos, I updated your application to the latest version. And as you can see, I am still having the same issue with exporting to PDF.

![IMG_20240216_152149.jpg](https://github.com/Akylas/OSS-DocumentScanner/assets/31793920/0e35db0a-35c5-46bf-a3d9-6efed841a5d0)

**Comment by farfromrefug** [comment]
@franco27 thanks a lot! will try to reproduce. Does it happen again if you create a new document like with importing the image you shared? Want to know if it is happening on any document

**Comment by franco27** [comment]
Yes, on the same document.
I imported the photo three times.
1. Imported the photo, added only one frame and applied the Bw filter.
2. The same. I imported the same photo.
3. The same ...

**Comment by farfromrefug** [comment]
@franco27 ok... And if you actually export the document. Is the filter correcly applied in the pdf? Or do you have the same issue with the exported pdf (and not just the preview)

**Comment by farfromrefug** [comment]
@franco27 i might have an idea. In the "preview" can you slide down to open the menu. Then see if black&white or color is selected? If black&white then it is normal. Black&White takes precedence over applied filter (which seems normal to me but maybe not very intuitive)

**Comment by franco27** [comment]
Yes, you are correct. It was selected in black and white in the preview settings, and when I changed it to color, the images now accurately reflect the images in the document.

![Screenshot_2024-02-22-16-26-25-648_com.akylas.documentscanner.jpg](https://github.com/Akylas/OSS-DocumentScanner/assets/31793920/f36c7256-5938-4f15-8d85-6668488682aa)

![IMG_20240222_162704.jpg](https://github.com/Akylas/OSS-DocumentScanner/assets/31793920/3825b74f-5753-4a4c-8909-d679e8c43cad)

**Comment by franco27** [comment]
Thank you very much
