### ISSUE TITLE
[FEATURE REQUEST] Fully disable the auto-crop function, by providing an ON/OFF toggle in Main Settings.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [Akylas/OSS-DocumentScanner#139]
**Is your feature request related to a problem? Please describe.**

Yes, I'm having problems. Let's say, I have 20 photos in the gallery & I want to make a PDF out of them. So, I open your app and click on the "Gallery +" on the bottom right corner. Then I select those 20 photos is the correct chronological order. Then the app auto-crops all of those 20 images according to it's mood. This is what my problem is. Why? Because those 20 photos are already perfect, they don't need cropping. Now, I have to swipe 20 times & click on "No crop" icon 20 times. I hope you understand my problem.
![ResizedImage_2024-02-22_06-49-22_8887](https://github.com/Akylas/OSS-DocumentScanner/assets/91815107/5d116f09-d06e-4aad-8ffd-43465172ce32)

**Describe the solution you'd like**

A simple ON/OFF toggle in the Main Settings that turns on/off the auto-crop function.

**Comment by farfromrefug** [comment]
@Aryan-Chauhan i added an on/off setting in the new Document Detection section of the settings. With it OFF you wont go through the cropping page at all. You document will automatically be added as the full captured image (can be quite big though!)

**Comment by Aryan-Chauhan** [comment]
> @Aryan-Chauhan i added an on/off setting in the new Document Detection section of the settings. With it OFF you wont go through the cropping page at all. You document will automatically be added as the full captured image (can be quite big though!)

What settings do I need to change?

**Comment by farfromrefug** [comment]
@Aryan-Chauhan not published yet :D coming today!

**Comment by Aryan-Chauhan** [comment]
> @Aryan-Chauhan the build is up on github! Will be on playstore/izzy tonight or tomorrow

Thank you for implementing my request so quickly!

This shows you want your app to work really well.
