### ISSUE TITLE
[BUG] Text overlapping in app.

### ISSUE THREAD

**Issue by eddieofny** [Akylas/OSS-DocumentScanner#141]
### Version

1.4.9 Build 51

### What platform are you using?

Android

### OS Version

Android 7.0

### What happened?

The text in the app is overlapping anywhere there are more than 2 lines of text in a field. I'm running this app on an LG K20 running stock Android 7. I'm using the v7a build of the app, installed via Obtainium.

![Screenshot_2024-02-22-09-56-56](https://github.com/Akylas/OSS-DocumentScanner/assets/98845254/30051c53-f5e8-4f2d-81bc-7e46006ea688)
![Screenshot_2024-02-22-09-57-04](https://github.com/Akylas/OSS-DocumentScanner/assets/98845254/702a733c-3b37-48d3-a697-99fc13c5a514)
![Screenshot_2024-02-22-09-57-08](https://github.com/Akylas/OSS-DocumentScanner/assets/98845254/96b69d28-e749-46b0-889b-2b951958ca49)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@eddieofny really sorry about that! will try to reproduce

**Comment by eddieofny** [comment]
No worries, the app work really well aside from that! My phone language is U.S. English.

**Comment by farfromrefug** [comment]
@eddieofny a new build is up on github which should fix it! (will be on playstore / izzy tonight or tomorrow)

**Comment by eddieofny** [comment]
Just updated, works perfectly now. Thanks!
