### ISSUE TITLE
[BUG]  Crash during adding pictures captured with batch capture

### ISSUE THREAD

**Issue by S-Joao-V** [Akylas/OSS-DocumentScanner#142]
### Version

v1.4.11 Build 52

### What platform are you using?

Android

### OS Version

14

### What happened?

After capturing multiple pictures with the batch capture feature, then selecting the add "V" button, and waiting, the app closed after a while, some details and steps:

Pictures taken without transformation - full color
Number of pictures taken - 46
After re-opening the app, the document for the batch that crashed is there, but with pictures missing - 31 of 46 present there.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@S-Joao-V almost certain it is a an out of memory issue.
i want to fix this one for good. I have an idea on how i could do that but it will require kind of major refactor.
I will definitely do it but it is going to take a bit of time. 
In the meantime you can add images in smaller batch if that is ok with you :s

**Comment by S-Joao-V** [comment]
@farfromrefug for sure, have been using 20-20 without issues.

**Comment by farfromrefug** [comment]
@S-Joao-V there is  a new version which should improve this a lot. It might still crash with a very big number of scans, but not even sure...
You can test if you want

**Comment by farfromrefug** [comment]
@S-Joao-V this should be definitively fixed in latest version!
