### ISSUE TITLE
[BUG] Delete not working on iOS

### ISSUE THREAD

**Issue by hellfire103** [Akylas/OSS-DocumentScanner#143]
### Version

1.1.0 Build 11

### What platform are you using?

iOS

### OS Version

iOS 17.3.1

### What happened?

I am unable to delete scans, as the dialog causes the menu to close, which then causes the dialog to close before I can tap "Delete".

https://github.com/Akylas/OSS-DocumentScanner/assets/67475141/7c7e47bf-8fbb-4223-b994-a109764dc136

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jacobgonzales20** [comment]
delete is also not working for me as well

https://github.com/Akylas/OSS-DocumentScanner/assets/122128828/0dd14fe8-a78e-4f14-b1be-84f3e31442ac

**Comment by farfromrefug** [comment]
@jacobgonzales20 thanks for the report! It is already fixed. Need to fix a few other iOS bugs then i ll release
