### ISSUE TITLE
[BUG] Crash during cammera scan

### ISSUE THREAD

**Issue by ernemir** [Akylas/OSS-DocumentScanner#145]
### Version

1.4.11 Build 52

### What platform are you using?

Android

### OS Version

Android 10

### What happened?

When I click on the camera icon to scan a document, the screen freezes.
The interface shows up, but the part that should show the camera capture is black.
I tried clearing the app cache, resetting permissions and restarting the phone without success.
![Screenshot_20240225-193611](https://github.com/Akylas/OSS-DocumentScanner/assets/14062438/271d5864-7c67-455a-a7d1-d770370edb46)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@ernemir thanks for reporting this! can you try to reproduce the issue with this build https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android ? (restart the app after the error to ensure the bug report is sent)

**Comment by ernemir** [comment]
Thanks for your reply.
I installed the test build and reproduced the issue. I restarted the application after the error so it sends the report.
I am not sure if the application sent the report. I can try again if it did not send.

**Comment by farfromrefug** [comment]
@ernemir thanks a lot for testing this. Let see if i can find it. What s your phone (your log is anonymous but i get your phone model so it can help me find it)

**Comment by ernemir** [comment]
It is a Motorola  Moto G7 plus (XT1965-2)

**Comment by farfromrefug** [comment]
@ernemir is this still happening with latest?

**Comment by ernemir** [comment]
It seems to work now. 
Thank you very much!!
