### ISSUE TITLE
[BUG] Pdf export,share, open and print are not working.

### ISSUE THREAD

**Issue by iamthelara** [Akylas/OSS-DocumentScanner#146]
### Version

1.4.11.52

### What platform are you using?

Android

### OS Version

13

### What happened?

A bug happened!
When I am trying to export pdf scanned documents. Scanned photos are whitened using your app. I have successfully exported in pdf other Scanned document which is not whitened.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamthelara** [comment]
![Uploading Screenshot_20240226_101844_OSS Document Scanner.jpg…]()

**Comment by iamthelara** [comment]
![Screenshot_20240226_101844_OSS Document Scanner](https://github.com/Akylas/OSS-DocumentScanner/assets/50659607/abd95de2-0969-49e4-a7f7-e0f17f0c7004)

**Comment by jacobgonzales20** [comment]
same issue here as well 

https://github.com/Akylas/OSS-DocumentScanner/assets/122128828/574a19dd-eaa9-42f1-af06-2dae0210a60f

**Comment by farfromrefug** [comment]
@iamthelara @jacobgonzales20 thanks for reporting this! can one of you try to reproduce the issue with this build https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android ? (restart the app after the error to ensure the bug report is sent)

**Comment by iamthelara** [comment]
@jacobgonzales20 I tried with build 53. Got same result. Let me  try mentioned one.

**Comment by iamthelara** [comment]
I can't install the test version on build 53. And I can't uninstall build 53 I have lots of documents scanned. Sorry

**Comment by farfromrefug** [comment]
@iamthelara dont worry i ll find a way! You installed from play store or github?

**Comment by farfromrefug** [comment]
@iamthelara this should be fixed in latest
