### ISSUE TITLE
[FEATURE REQUEST] Scan several pages in the same PDF

### ISSUE THREAD

**Issue by gauffke** [Akylas/OSS-DocumentScanner#147]
Just discovered the app on iOS (17.3.1), version 1.1.1 build 12. Co fears for the splendid work!

i cannot find a way to scan several pages in a row and have them in the same PDF. Did I miss something? If not, could you consider this?

Many thanks!

**Comment by farfromrefug** [comment]
@gauffke i see bug reports on iOS which might be related to this.
Without bug there is 2 ways of doing this:
* in the camera view click the bottom left icon to enable batch mode.
* in an existing document view you can use the 2 floating at the bottom right to add from camera or from image

**Comment by gauffke** [comment]
Thank you!
