### ISSUE TITLE
[BUG] Red Text In Exported PDF

### ISSUE THREAD

**Issue by eglia** [Akylas/OSS-DocumentScanner#151]
### Version

1.4.12

### OS Version

GrapheneOS (Android 14)

### What happened?

In exported PDFs, the OCRd text ist visible in red over the document, making the document unreadable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@eglia thanks for the report will be fixed in next version. You installed from the play store right?

**Comment by eglia** [comment]
Yes, I installed from the play store. Thank you for the quick fix!

**Comment by farfromrefug** [comment]
@eglia fixed in latest
