### ISSUE TITLE
[BUG] Miss aligned icons

### ISSUE THREAD

**Issue by Sureshgorai25** [Akylas/OSS-DocumentScanner#152]
### Version

Latest 1.4.12.53

### What platform are you using?

Android

### OS Version

Moto MyUX Android 14

### What happened?

Icons are missing aligned with the text in the settings
![Screenshot_20240229-115815](https://github.com/Akylas/OSS-DocumentScanner/assets/93507842/206796f6-7a69-4e45-a8ad-b93f2da71301)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@Sureshgorai25 fixed in latest
