### ISSUE TITLE
Edge-to-Edge [FEATURE REQUEST]

### ISSUE THREAD

**Issue by b3il0** [Akylas/OSS-DocumentScanner#154]
Hey, I think it would look visually appealing if the app didn't have a black navigation bar but rather a transparent one (Edge-to-Edge) as a background. 

Like documented here: https://developer.android.com/jetpack/compose/layouts/insets

![1000043843](https://github.com/Akylas/OSS-DocumentScanner/assets/37301674/1bb25982-3175-4277-ba91-59d02cfd97a5)
![1000043844](https://github.com/Akylas/OSS-DocumentScanner/assets/37301674/01be1a61-33fe-4031-b356-f812b9cbf3a4)

**Comment by farfromrefug** [comment]
@b3il0 very nice will implement that!

**Comment by farfromrefug** [comment]
@b3il0 it is in latest version!

**Comment by b3il0** [comment]
@farfromrefug already using the update. Very good. Looks fantastic.
