### ISSUE TITLE
[BUG] Reopen the app white screen after switching languages

### ISSUE THREAD

**Issue by pigyee** [Akylas/OSS-DocumentScanner#160]
### Version

1.4.15.56

### What platform are you using?

Android

### OS Version

android10 api29 

### What happened?

A bug happened!
Reopen the app white screen after switching languages

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@pigyee sorry for the late answer. 
I am trying to understand your issue:
* when you switch language the app becomes white right away? 
* or does it work and change languages correctly at first. But then gives a white screen when you close and re open the app?
Thanks

**Comment by pigyee** [comment]
> @pigyee sorry for the late answer. I am trying to understand your issue:
> 
>     * when you switch language the app becomes white right away?
> 
>     * or does it work and change languages correctly at first. But then gives a white screen when you close and re open the app?
>       Thanks

The second one kills the process after switching languages, and then the white screen

**Comment by pigyee** [comment]
### More info

- The error only occurs when switching to Chinese
### Steps to reproduce

1. Open the app and switch the language to Chinese
2. Termination of Proceedings
3. Open the program and a bug occurs

### 更多信息

- 只有切换到中文才会发生错误
### 复现步骤

1. 打开app,切换语言到中文
2. 终止程序
3.打开程序，发生bug

**Comment by farfromrefug** [comment]
@pigyee thanks a lot for the details. Will test right now

**Comment by farfromrefug** [comment]
@pigyee i think i fixed it. Will be in the next version
