### ISSUE TITLE
[BUG] Crash when trying to transform (enchange) whole "collection" of scans

### ISSUE THREAD

**Issue by tadekdudek** [Akylas/OSS-DocumentScanner#162]
### Version

1.4.15 build 56

### What platform are you using?

Android

### OS Version

Android 14 / LineageOS 21 (no GApps)

### What happened?

Like in title, app crashes and android kills all background processes (also those with disabled battery optimization) when I'm trying to transform all scans in a "collection".

### Relevant log output

```shell
Unfortunately, I can't provide logs as I currently dont have access to a PC and trying to capture logs with Termux (also with wakelock), AppManager and android's built in bug report (because all they are killed when crash). I'll capture them later with hope that adb logcat process won't be killed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@tadekdudek it is a memory issue. Right now the app is not really optimized for such big operations.
Out of curiosity how many documents? pages total? (approximately)

**Comment by farfromrefug** [comment]
@tadekdudek there is a new version on the app which could be fixing a lot of memory issues. Please let me know if it still crashes

**Comment by tadekdudek** [comment]
> @tadekdudek there is a new version on the app which could be fixing a lot of memory issues. Please let me know if it still crashes

It still crashes in 1.5.0 build 57.

> @tadekdudek it is a memory issue. Right now the app is not really optimized for such big operations. Out of curiosity how many documents? pages total? (approximately)

It's about 40 images

**Comment by farfromrefug** [comment]
@tadekdudek ok too bad will try to reproduce. Are you images big? what s the average image size  ?

**Comment by tadekdudek** [comment]
Mostly about 2200x3500

**Comment by farfromrefug** [comment]
@tadekdudek just published a new version. Tested with 80 items and it didnt crash. Hopefully it works for you too

**Comment by tomaszk8266** [comment]
For me crashes with 10 images, 8 works fine
