### ISSUE TITLE
[BUG] UnknownHostException when downloading Tesseract trained data using proxy

### ISSUE THREAD

**Issue by eht16** [Akylas/OSS-DocumentScanner#164]
### Version

1.4.15.56

### What platform are you using?

Android

### OS Version

GrapheneOS Android 13

### What happened?

When trying to download the trained data for Tesseract from within the app, an "UnknownHostException" is thrown.

This happens when a global proxy is set via "settings put global http_proxy proxy.example.com:8080"

The address in the error message is my configured proxy hostname.

### Relevant log output

```shell
03-17 14:51:44.732  1630  2686 D CoreBackPreview: Window{1bf2af0 u0 com.akylas.documentscanner/com.akylas.documentscanner.MainActivity}: Setting back callback null
03-17 14:51:44.737  1630  2686 W InputManager-JNI: Input channel object '1bf2af0 com.akylas.documentscanner/com.akylas.documentscanner.MainActivity (client)' was disposed without first being removed with the input manager!
03-17 14:51:44.753  1630  1773 V WindowManager: Unknown focus tokens, dropping reportFocusChanged
03-17 14:51:44.796 31016 31057 W Parcel  : Expecting binder but got null!
03-17 14:51:44.803  1630  3360 D CoreBackPreview: Window{deca04e u0 com.akylas.documentscanner/com.akylas.documentscanner.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@4c98a68, mPriority=0}
03-17 14:51:44.842  1630  3360 D CoreBackPreview: Window{deca04e u0 com.akylas.documentscanner/com.akylas.documentscanner.MainActivity}: Setting back callback null
03-17 14:51:44.844  1630  3360 W InputManager-JNI: Input channel object 'deca04e com.akylas.documentscanner/com.akylas.documentscanner.MainActivity (client)' was disposed without first being removed with the input manager!
03-17 14:51:44.876 31016 31057 W Parcel  : Expecting binder but got null!
03-17 14:51:44.880  1630  2686 D CoreBackPreview: Window{501f457 u0 com.akylas.documentscanner/com.akylas.documentscanner.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@ad35629, mPriority=0}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

![bug_proxy_oss-ds](https://github.com/Akylas/OSS-DocumentScanner/assets/617017/9be44ce5-e9d9-46e2-9a74-af8868cfadd2)

**Comment by farfromrefug** [comment]
@eht16 not sure what I can do about this. could this be an issue with your proxy being unable to contact github?
I dont do anything special with http request so I guess they should work with proxy.
can you access github using your global proxy from your browser?

**Comment by eht16** [comment]
The proxy server can contact Github just fine, it works via browser and any other app and it can be resolved via DNS.

**Comment by eht16** [comment]
Argh, I denied the network permission when installing it.

After allowing the app network access, it works perfectly.
Sorry for wasting your time :(.
