### ISSUE TITLE
[FEATURE REQUEST] Move and Reorder Scanned Pages Around

### ISSUE THREAD

**Issue by liluzibird** [Akylas/OSS-DocumentScanner#173]
The ability to move pages around after finished scanning would be a huge improvement. Say you snapped images A,B,C but then you realized you wanted C to be at the beginning so you want it in the order of C,A,B. Currently, to do this, one would need to retake everything again. It's not ideal.

**Describe the solution you'd like**
Allow dragging around of the pages around by tap and holding onto the pages. 

**Describe alternatives you've considered**
Allow an option for moving and the app will go into moving mode, so the user can drag the pages around.

**Additional context**
![image](https://github.com/Akylas/OSS-DocumentScanner/assets/57073805/125491ff-a5cf-4736-83e8-5841a4114885)

**Comment by liluzibird** [comment]
Ok, apparently, this was already implemented (https://github.com/Akylas/OSS-DocumentScanner/issues/46#issuecomment-1901130069). I had to read that comment to figure out how to get it to work (press and hold the page number and drag around). I would like to propose a move icon on the image or something because it wasn't easy to figure this out.

**Comment by liluzibird** [comment]
> @liluzibird thanks for creating this issue. Yes i am not happy with the current UX solution. And it works even worse on iOS. I will think about a move icon. Just felt it was not looking good :D

If there's anything I can do to help this project, I would be happy to do so, but I have very rudimentary coding skills and only know the basics of C++ and Java. I haven't ever dealt with a code base this large, so I don't know how to implement this improved UX feature.

**Comment by farfromrefug** [comment]
@liluzibird Any help is appreciated. If you know of C++ there is one part where you can help improve the app without even building the app. It is the image processing part:
* image processing for detecting the document "corners"
* image cropping
* image filters likes whitepaper

If you are interested those can very easily be tested using vscode/cmake:
* clone 
* open in vscode with `CMake Tools` installed`
* change the vscode workspace setting to tell it in which folder to look for test images (i dont commit them to not make the repo too big)
* run with command `CMake Debug` 
* it runs the cpp file `cpp/cpp_test_app/scanner.cpp

Now if you want to work more on the app itself. It requires quite a bit more environment setup https://github.com/Akylas/OSS-DocumentScanner/issues/148. But it is doable and i can help.
So you know the app is actually not native "directly'. It uses Nativescript. So the app is developped in TS/Svelte for the UX part. All the image processing part is in Kotlin/C++

**Comment by liluzibird** [comment]
Hey there, idk if I should make a new issue or continue with this one. I'm trying to just get started and have git cloned and installed cmake tools, however, I don't know what the 3rd bullet point "change the vscode workspace setting to tell it in which folder to look for test images (i dont commit them to not make the repo too big)" means. Do I put any random images into /images?

Sorry, if I'm causing more issues than helping. I genuinely want to help.

**Comment by farfromrefug** [comment]
@liluzibird dont worry you are right to ask.
The CPP example app takes 2 arguments :
* a folder containing images (what lever naming, extension supported by opencv). The second arg is the filename of one of the images in that folder to start the app on.
Then within the app you LL be able to change images (from within that folder) to test the algo.
So to summarise create a folder with any image you want to test the algo on and use that folder name within vscode workspace settings
