### ISSUE TITLE
[BUG] Imported photos deleted with document without prompt.

### ISSUE THREAD

**Issue by cheintz** [Akylas/OSS-DocumentScanner#174]
### Version

1.5.5.62

### What platform are you using?

Android

### OS Version

GrapheneOS latest (Android 14)

### What happened?

Imported photos deleted when parent document was deleted, without warning

### Relevant log output

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@cheintz are you saying the actual imported image (like the file in Download folder) where deleted when you deleted the document?
If so this is really bad and i am really sorry. Will look at it right away

**Comment by cheintz** [comment]
Thanks for the quick reply!

I believe that is what happened (deleted images out of the camera roll). I had a bunch of similar photos, and couldn't find some of the pages. I will try to reproduce  in a few days.

I ended up re-scanning everything in a different app, anyway, since I was in a bit of a hurry and couldn't get logs of other bugs I was having. 

Thank you for your efforts in making an OSS scanning app!

**Comment by farfromrefug** [comment]
> Thanks for the quick reply!
> 
> I believe that is what happened (deleted images out of the camera roll). I had a bunch of similar photos, and couldn't find some of the pages. I will try to reproduce in a few days.
> 
> I ended up re-scanning everything in a different app, anyway, since I was in a bit of a hurry and couldn't get logs of other bugs I was having.
> 
> Thank you for your efforts in making an OSS scanning app!

OK thank you for reporting this. Very important. Will run some tests on my side. Let me know if you find more info!

**Comment by cheintz** [comment]
Could not reproduce. Sorry for stressing you out with this.
