### ISSUE TITLE
Oly for photos? 

### ISSUE THREAD

**Issue by katastrophe92** [Akylas/OSS-DocumentScanner#175]
Hey there! Does this ocr reader doesn't open documents like PDF?

**Comment by farfromrefug** [comment]
@katastrophe92 are you saying you would like to import PDF within the app to use OCR on it?

**Comment by katastrophe92** [comment]
> @katastrophe92 are you saying you would like to import PDF within the app to use OCR on it?

Exactly

**Comment by farfromrefug** [comment]
@katastrophe92 ok so right now no you can't import PDFs. I can think about it but it could be quite a lot of work. Not even sure how that would be implemented (PDFs can have images, texts...) .
There is already an opened issue about this https://github.com/Akylas/OSS-DocumentScanner/issues/138.
So i will close yours if you dont mind. And i ll think about how to achieve this.

**Comment by katastrophe92** [comment]
I will still use it cause it is verry useful and don't need to use a F close sorced app to OCR a pic. Thanks for you're reply 😘

**Comment by farfromrefug** [comment]
@katastrophe92  it is now implemented in latest android version (ios to come later)

**Comment by katastrophe92** [comment]
> @katastrophe92  it is now implemented in latest android version (ios to come later)

Cool!  Thanks
