### ISSUE TITLE
Merge PDFs

### ISSUE THREAD

**Issue by NripPrajapat** [Akylas/OSS-DocumentScanner#179]
Please add an option, that enables the use to import 2 and more PDFs and then merge both of them into a single one, also it would be only practical to let user reorder the pages in those PDFs.

**Comment by farfromrefug** [comment]
@NripPrajapat it is for now out of the scope of this app. It is not a PDF manager. That app is a document manager with an export to PDF option.
I might add an option to import PDF in the future which in a sense would solve this.
I ll close this for now as wont implement but i keep it in mind with import PDF
