### ISSUE TITLE
[FEATURE REQUEST] OCR PROBLEM 

### ISSUE THREAD

**Issue by Kumar808** [Akylas/OSS-DocumentScanner#182]
Ocr engine of this app is unable to Detect Indian Currency Sign "₹" .
Can you fix it ?
It is detecting "₹" as number "7" .
Please fix it as soon as possible.

**Comment by farfromrefug** [comment]
@Kumar808 Sorry  i cant fix it. You can look at [tesseract](https://github.com/tesseract-ocr/tesseract). It is the OCR engine
