### ISSUE TITLE
[FEATURE REQUEST] way to sync export images/PDF to a folder on the phone

### ISSUE THREAD

**Issue by Nionor** [Akylas/OSS-DocumentScanner#184]
**Is your feature request related to a problem? Please describe.**
Can't access saved files due to Android storage permissions.

**Describe the solution you'd like**
Maybe instead of choosing Internal storage/SD Card which defaults to .../Android/data/com.akylas.documentscanner/file, make a third option to select a specific folder.

**Comment by Nionor** [comment]
Can't you split it up so you have the db where it is now and only put the images and documents  in an accessible location?

**Comment by farfromrefug** [comment]
@Nionor It is a possibility but wont be of much use to you. 
You need to understand that the "data" folder and the images in there might not correspond to the image you would export from the app. It is missing information like filters (bw, sepia...) and possibly more things in the future.
Custom storage location would mainly be to use the same data after app re-installation or using new phone with same sd card

**Comment by Nionor** [comment]
Ah I see, but is that the same data that is synced with WebDAV?

**Comment by farfromrefug** [comment]
@Nionor Yes it is. Only a "backup" thing.
If what you want is a way to "sync" "exported" images automatically then it is kind of another feature request. 
Possible but requires some design and work (like what happen if you delete a page, what file naming rules so that image gets updated if you change filter or something...)
But it is on my TODO list!

**Comment by Nionor** [comment]
Ok cool, no we are on the same page then as a backup solution but I just didn't know the inner workings.
But don't put too much time on this, I just thought it would be a nice way to have alternative ways to make a backup.
An alternative could maybe be to use the same functionality as the WebDAV sync but just sync to a local folder?

The sync for exported images works fine as it is I think since there you can choose any folder you like.

On a side note, I added Swedish translation but I saw in the PR that the json was added but empty, is there something I need to do on the Weblate page to commit it or something?
First time using Weblate so I'm a noob there.

**Comment by farfromrefug** [comment]
@Nionor indeed i see it is done on weblate. Might take a bit of time for the PR to be created with the content. Not sure...
Will check it

**Comment by farfromrefug** [comment]
@Nionor we can close this right?

**Comment by Nionor** [comment]
Still think it would be nice to have another automatic backup solution other then WebDAV, but maybe something for later.

**Comment by farfromrefug** [comment]
Yes I will implement it! Just need time
