### ISSUE TITLE
[BUG]  what's the use of internet permission?

### ISSUE THREAD

**Issue by Bertklq1** [Akylas/OSS-DocumentScanner#192]
### Version

Latest

### What platform are you using?

Android

### OS Version

Lineageos 14

### What happened?

A bug happened!!!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@Bertklq1 good question. It is here because of the webdav sync/backup feature

**Comment by Bertklq1** [comment]
> @Bertklq1 good question. It is here because of the webdav sync/backup feature

Ok got it.

Any plan on making 100% offline variant of the app?

**Comment by farfromrefug** [comment]
What s the issue with this version ? I mean yes it has internet permission but :
* fully open source so you know what I do
* you can still block and network access from android

**Comment by farfromrefug** [comment]
@Bertklq1 actually thought about that. The internet permission is also necessary to download OCR models from github

**Comment by farfromrefug** [comment]
@Bertklq1 i ll close this issue if you dont mind. feel like i answered you

**Comment by farfromrefug** [comment]
> > The internet permission is also necessary to download OCR models from github
> 
> You can adding them directly in the build.
> 
> So internet is unnecessary. I don't use webdav, so I am searching for a 100% offline version.



> > The internet permission is also necessary to download OCR models from github
> 
> You can adding them directly in the build.
> 
> So internet is unnecessary. I don't use webdav, so I am searching for a 100% offline version.



> > The internet permission is also necessary to download OCR models from github
> 
> You can adding them directly in the build.
> 
> So internet is unnecessary. I don't use webdav, so I am searching for a 100% offline version.

No i cant add them in the app. I wont add all OCR models for all language. The app would get too big. makes no sense.

The app is already 100% offline if you dont use the OCR feature. Even if you use it once you downloaded the model, it is 100% offline

**Comment by farfromrefug** [comment]
> The app is not "air gapped". It has internet permission.
> 
> No problem, it is not what I searching for.
> 
> Below the evidence. It is a fact, not an assumption.
> 
> ![1000120018](https://github.com/user-attachments/assets/b9d82846-4307-46ea-8839-a453930d2baa)
> 

That text just mention what the app can do with the permission. Not what it does!
The code is 100% open source and you can easily see the requests it makes. Plus being  the dev inknow the request it makes. I can assure you the app can be used 100% offline (which is my use case)
