### ISSUE TITLE
[FEATURE REQUEST]x86_64 version request

### ISSUE THREAD

**Issue by wentywenty** [Akylas/OSS-DocumentScanner#193]
cant install on x86_64 devices

Can you add support for x86_64 platform?

thankyou

**Comment by farfromrefug** [comment]
@wentywenty didn't know there were really that many devices with that arch. Will add it. Though it will only be On github for now (and play store)

**Comment by farfromrefug** [comment]
@wentywenty just made the first release https://github.com/Akylas/OSS-DocumentScanner/releases/tag/com.akylas.documentscanner%2Fandroid%2Fgithub%2F1.7.0%2F70

**Comment by wentywenty** [comment]
thankyou
