### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xtoes** [Akylas/OSS-DocumentScanner#195]
### Version

1.4.0 build 22

### What platform are you using?

iOS

### OS Version

iPhone 12 iOS 17.3.1

### What happened?

Whenever I try to scan a document, the app immediately crashes regardless of auto scan being on/off.

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@xtoes sorry to hear that. Will try to reproduce/fix tomorrow

**Comment by farfromrefug** [comment]
@xtoes not in a release version from the store . but dont worry will be fixed tomorrow

**Comment by xtoes** [comment]
Thanks for fixing it!
