### ISSUE TITLE
[BUG] Bottom part of app is covered by android navigation buttons

### ISSUE THREAD

**Issue by SanskritFritz** [Akylas/OSS-DocumentScanner#198]
### Version

OSS Document Scanner: 1.7.1 Build 71 from Github

### What platform are you using?

Android

### OS Version

LinageOS 18.1 (Android 11)

### What happened?

The bottom part of the app is covered by android navigation buttons, hence it is very cumbersome to press any button on the bottom (for example the green Camera button on the start page).
![Screenshot_20240513-105748_OSS_Document_Scanner](https://github.com/Akylas/OSS-DocumentScanner/assets/209814/8c49f085-84ae-427d-9b12-78a92ab61f39)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SanskritFritz** [comment]
More info: no other app behaves this way on my system, only OSS Document Scanner has this problem.

**Comment by farfromrefug** [comment]
@SanskritFritz it is a bug ! Should not happen. But have started after a recent change . will ftry to reproduce then fix

**Comment by SanskritFritz** [comment]
Thank you for caring!
Can you reproduce it? I thought I was the only one having this issue.

**Comment by farfromrefug** [comment]
@SanskritFritz yes thanks i did reproduce it and fixed it! Will be in next version (hopefully today)

**Comment by SanskritFritz** [comment]
I just tried the new release, yes, thank you, it is perfect now!
