### ISSUE TITLE
[FEATURE REQUEST] Clarify icons

### ISSUE THREAD

**Issue by ghost** [Akylas/OSS-DocumentScanner#209]
For the flash icon, the first three are commonly understood from other camera apps as something like "flash never on" "flash always on" and "flash on automatically when needed". However, there's a fourth flash icon in this app that is leaving me scratching my head. The icon has an eye on it. Is it something about red eye reduction?

For the batch mode icon, I suggest the text below icons should read "Single Page" or "Batch Mode". This would better clarify the functionality for the icons.

**Comment by farfromrefug** [comment]
@48-mq it is red eye. Which does not really make sense for that app :D Will remove it
