### ISSUE TITLE
[BUG] Auto scan not turning off consistenly

### ISSUE THREAD

**Issue by ghost** [Akylas/OSS-DocumentScanner#210]
### Version

1.8.3.74

### What platform are you using?

Android

### OS Version

Stock Android 14 on Pixel 7 Pro

### What happened?

I thought I have auto scan turned off in Settings -> Auto scan -> Discover and add documents automatically. But occasionally the app still captures only a portion of what the camera screen shows, and then doesn't show the crop screen with the magnifier tool.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@48-mq that s different from auto scan:
* auto-scan: if a "region" is discovered and not moving for a second then it will be automatically captured without you having to press the capture button
* what you are seeing is a different behavior: if you capture, without batch mode, and a region is discovered matching some criteria (size, ...) then it is automatically added without you having to confirm the region. It is for things to get faster

The second feature can be deactivated in document-detection settings (force crop confirmation or something like that).
