### ISSUE TITLE
[BUG] Camera settings sheet shows name of string resource instead of translation for some fields

### ISSUE THREAD

**Issue by min7-i** [Akylas/OSS-DocumentScanner#212]
### Version

1.8.4 Build 75

### What platform are you using?

Android

### OS Version

Android 14 QPR2 (GrapheneOS)

### What happened?

When taking a picture with the app-internal camera, the chosen values for "preview stretch" and "view size" in camera settings use the internal name of the string instead of the translation. The values in the dropdown itself show the correct translations.

| internal string for chosen value | correct translation for values in dropdown |
| --- | --- |
| ![camera settings 1](https://github.com/Akylas/OSS-DocumentScanner/assets/97251923/08ee2dbd-cfd2-4450-97dd-b36cc9574746) | ![camera settings 2](https://github.com/Akylas/OSS-DocumentScanner/assets/97251923/b27f0549-65e8-4dc0-ac2c-9a3db69652a1) |

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@min7-i thanks it is now fixed!
