### ISSUE TITLE
images folder configurable

### ISSUE THREAD

**Issue by edmundlaugasson** [Akylas/OSS-DocumentScanner#216]
**Is your feature request related to a problem? Please describe.**
Cannot find images in folder and use them with other apps.

**Describe the solution you'd like**
Please, make images folder configurable. There is a need to browse images in another app. Similarly to PDF, please allow to define exact folder where to store images, under Settings. Currently impossible to find the folder, where images are stored. Not in root or Pictures folder. Even search didn't find.

**Describe alternatives you've considered**
Manual export even images.

**Additional context**
Currently even when exporting images, cannot choose a folder. Export is currently exporting to Downloads folder among other files, which is quite annoying. Would be good to configure also that location.
Using Android 11. Newest app itself from Google play.

**Comment by farfromrefug** [comment]
@edmundlaugasson this wont be done due to Secure Access Storage restrictions. The app data (images, db,...) is stored in the app internal folder. You can choose the export folder for images.
I plan on adding a "sync" feature which would automatically sync images/pdf of documents into a phone folder.
However not sure when this will happen. Those implementations take time and without funding it is quite hard to give so much time to my apps.
Hope you understand

**Comment by edmundlaugasson** [comment]
This can be done via same way like currently is PDF folder selection - first time selecting, user will provide access permissions to chosen folder and app remembers it.
Sync could be a workaround of direct saving.
I hope the community will appreciate your app and will contribute in both coding and funding. Making app available in [F-droid](https://f-droid.org/) would help to spread the app and engage more people.
I have programming bachelor students (ca 900) who can be involved. Certainly they are not as experienced as professionals but is an option you can consider. Twice per year, September, January they start to search thesis topic. There would be possible to split large tasks into smaller pieces.

**Comment by farfromrefug** [comment]
@edmundlaugasson I know making it available on F-droid would help. But i have big concerns about the energy cost of F-droid (building every thing used in your app can take ages). So i prefer to stick with izzy right now.

**Comment by Korb** [comment]
>  I plan on adding a "sync" feature

@farfromrefug, as I understand it, synchronization has been added. How does it work? "Mirror A → B (incremental)" / "Mirror B → A (incremental)", "Synchronize A ↔ B (incremental)", "Synchronize A ↔ B (custom)", "Backup A → B (full)" / "Restore B → A (full)", "Contribute A → B (incremental)" / "Contribute B → A (incremental)" or "Synchronize A → B (custom)" / "Synchronize B → A (custom)"?

**Comment by farfromrefug** [comment]
@Korb i dont really know the différence between each case :) 
Data sync is a mirror . if you delete it is deleted on the other side

**Comment by Korb** [comment]
OK, `side`, `mirror`. Which?

If `A` is the application's database, and `B` is a user-specified folder, then:

1. Adding/deleting/renaming/moving a file in `A` also adds/deletes/renames/moves it to `B`;
2. Adding/deleting/renaming/moving a file in `B` also adds/deletes/renames/moves it to `A`.

Correct? So, the application calculates file checksums to determine whether a file, for example, wasn't added, but simply renamed? Plus filtering by acceptable file types to prevent unsupported files added to `B` from attempting to upload to the database?
