### ISSUE TITLE
compress ratio of PNG

### ISSUE THREAD

**Issue by edmundlaugasson** [Akylas/OSS-DocumentScanner#217]
**Is your feature request related to a problem? Please describe.**
Images are quite large in file size. Then also exported PDF comes too large.

**Describe the solution you'd like**
Please allow to change image compress ratio in case of PNG. Currently same quality setting from JPG applies also to PNG. Quality setting for PNG could be but compression ratio is important to reduce file size.

**Describe alternatives you've considered**
Use lossy JPG format and reduce it's quality.

**Additional context**
JPG loses quality on every saving. PNG does not but if poorly compressed, images and also exported PDF will come too large.
Using Android 11. Newest app itself from Google play.

**Comment by farfromrefug** [comment]
@edmundlaugasson PNG is not compressed on android it is lossless. I dont plan on adding PNG compression right now.

**Comment by edmundlaugasson** [comment]
that might be true - https://stackoverflow.com/questions/39793619/is-there-any-way-to-reduce-png-size

**Comment by farfromrefug** [comment]
@edmundlaugasson can we close this as wont do?
