### ISSUE TITLE
renaming option

### ISSUE THREAD

**Issue by edmundlaugasson** [Akylas/OSS-DocumentScanner#221]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Renaming option would be expected: either selecting image(s) among others or opening it.

**Describe alternatives you've considered**
None as cannot determine where images are stored.

**Additional context**
Using Android 11. Newest app itself from Google play.

**Comment by farfromrefug** [comment]
@edmundlaugasson  what do you want to rename? THe document name? If so you can already do that by clicking on the document name while viewing it

**Comment by edmundlaugasson** [comment]
That's true - file I can rename in that way. Would propose to allow rename a file without opening it by just tapping and holding on it to select and then under 3-dot menu is rename choice.
Same applies to collection name, which is created by date and time when it started. Currently not possible to rename collection - at least I could not find it.

**Comment by farfromrefug** [comment]
@edmundlaugasson What do you mean by collection ? 
To clarify the app as the notion of :
* document: metadata + list of pages
* page

Both entities have a "name" field. But for now only the document "name" can be changed (the page name is not really used yet).

**Comment by edmundlaugasson** [comment]
Collection - before entering to see images (has date and time in name), might be also page in your terms.
When opening program, will see that "collection". When opening, we see images. Then also image can be opened.

**Comment by farfromrefug** [comment]
@edmundlaugasson can this be closed? i feel like what you want is already implemented
