### ISSUE TITLE
[BUG] Closing camera in batch mode leads to data lost

### ISSUE THREAD

**Issue by BaumiCoder** [Akylas/OSS-DocumentScanner#223]
### Version

1.8.4 Build 75

### What platform are you using?

Android

### OS Version

/e/OS 2.0 (based on Android 12)

### What happened?

1. I open the camera in the app with activated batch mode.
2. I take photos of several pages of longer document.
3. As I was finished I accidentally tap on the cross in the upper left corner instead of the check mark in the lower right corner.
4. All photos are lost.

If you already have taken photos there should be some confirmation dialog when closing with the cross that warns before the photos are lost.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@BaumiCoder sorry that you lost everything... Will add the confirmation

**Comment by farfromrefug** [comment]
@BaumiCoder i added the confirmation in latest. Hope you wont get into issues anymore!

**Comment by BaumiCoder** [comment]
@farfromrefug Thank you for the fast bugfix.
