### ISSUE TITLE
[BUG] wrong preview on screen after changing the aspect ratio

### ISSUE THREAD

**Issue by TuTiuTe** [Akylas/OSS-DocumentScanner#228]
### Version

1.9.1.77

### What platform are you using?

Android

### OS Version

Crdroid 14

### What happened?

After chaning thr aspect ratio in the settings, the cropping area on screen is displayced upwards
This is a very minor bug as it only affects the preview, not the image once it is cropped
![Screenshot_20240602-084826_OSS Document Scanner](https://github.com/Akylas/OSS-DocumentScanner/assets/143942440/16f0371a-e47d-4ac0-ba9d-a35eb37b46a4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@TuTiuTe thanks for the report. Does the "issue" persist after closing the app and opening again ? (the aspect ratio setting should persist)

**Comment by TuTiuTe** [comment]
Yep, even after a force stop through the system settings

**Comment by farfromrefug** [comment]
@TuTiuTe Just published a new version which should fix this.
Thanks for reporting!
