### ISSUE TITLE
[BUG] Whats up with the new release?

### ISSUE THREAD

**Issue by firefoxlover** [Akylas/OSS-DocumentScanner#232]
### Version

The release 3 hours ago has a different name. Is this wanted or in the wrong repo?

It has a different app name which causes trouble.

### OS Version

A

### What happened?

A

### Relevant log output

```shell
A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@firefoxlover it is à new baby app based on the same code. It is to handle cards

**Comment by kvmgithub** [comment]
At least rename the files appropriately. 
![ImageToolbox_2024-06-12_08-57-21_2668](https://github.com/Akylas/OSS-DocumentScanner/assets/62821128/02228ec9-45ab-4f0d-8fba-59667d69d4c7)

**Comment by farfromrefug** [comment]
@kvmgithub what s that screenshot? The apps are named correctly. Everything is separated

**Comment by kvmgithub** [comment]
It is [Obtainium](https://github.com/ImranR98/Obtainium?tab=readme-ov-file).
And no, the apps are all named app-arm64-v8a-release.apk, app-armeabi-v7a-release.apk or app-x86_64-release.apk.

**Comment by farfromrefug** [comment]
@kvmgithub you are talking file name, and those should not be an issue. The apps are named correctly. The issue is with Obtainium not supporting monorepo. Every single release is seen as a new app release. Opening an issue there

**Comment by farfromrefug** [comment]
@kvmgithub https://github.com/ImranR98/Obtainium/issues/1666

**Comment by farfromrefug** [comment]
@kvmgithub about github latest tag, yes you are right and it is the same of all monorepo. Nothing i can do about this.

**Comment by SanskritFritz** [comment]
@firefoxlover As a workaround you can put "OSS Document Scanner" to the field "Filter release title" in the config in Obtainium.

**Comment by kvmgithub** [comment]
@SanskritFritz I tried filtering by release title or notes before, that resulted in the right picture in [https://github.com/Akylas/OSS-DocumentScanner/issues/232#issuecomment-2162255189](my first comment). This time it worked.

**Comment by farfromrefug** [comment]
@SanskritFritz @kvmgithub seeing it uses a regexp event `Scanner` is enough.
I could add a note in the readme

**Comment by kvmgithub** [comment]
@SanskritFritz I tried filtering by release title or notes before, that resulted in the right picture [in my first comment](https://github.com/Akylas/OSS-DocumentScanner/issues/232#issuecomment-2162255189_). This time it worked.

**Comment by firefoxlover** [comment]
Yeah same here, it now gives me constant "no version found" errors.

@farfromrefug I appreciate your app but releasing 2 apps in the same releases leads to confusion with likely a lot of apps. Especially as the .apk files are named the same.

**Comment by farfromrefug** [comment]
@firefoxlover just tested with obtainium latest and it works fine here. I see my 2 apps correctly.
Now about the naming i understand your point. But it is also very important to note that it is 100% easier for me to releases those apps that way. Which means i can spend more time on features (dont forget i am not paid, very little donations, for all that i do) and bug fixes.
As for the file name. I will look if i can change that, however i am far from the only one using those names (default build names) https://github.com/zhanghai/MaterialFiles/releases

**Comment by firefoxlover** [comment]
@farfromrefug I will try adding it again, maybe that helps.

The app name is not a problem. Obtainium just uses the Github metadata for the app name I guess and uses the latest tag for releases.

**Comment by kvmgithub** [comment]
@firefoxlover as already stated, [this](https://github.com/Akylas/OSS-DocumentScanner/issues/232#issuecomment-2162364510) or even [this](https://github.com/Akylas/OSS-DocumentScanner/issues/232#issuecomment-2162382572) worked. I had to add it again to obtainium though, as it wanted to get the wrong version the first time and stated wrong version code the second time.

**Comment by firefoxlover** [comment]
Ok I tried it again. When adding the app new it detects the latest APK and automatically switches to this CardWallet.

**Comment by kvmgithub** [comment]
@firefoxlover Do what is shown left to get what is shown right. 
![ImageToolbox_2024-06-12_16-08-31_5716](https://github.com/Akylas/OSS-DocumentScanner/assets/62821128/c5755ef5-7723-42de-90a5-728a7731fe60)

**Comment by exstntlmsnthrp** [comment]
I agree with @firefoxlover that this is very confusing. No one uses the same, solitary repo for multiple projects. It's not that difficult to setup another repo and build process. I don't need or want a card scanner. 

You're going to drive people away from the project by doing this. I'm receiving GitHub notifications that a new version of OSS document scanner is available and then find out it's this. Please separate into 2 repos.

**Comment by farfromrefug** [comment]
@exstntlmsnthrp Sorry you dont like it. But i wont change it. And please dont say it is not difficult when you dont know the implications.
Obtainium is 100% capable of handling both apps as explained in this thread.

**Comment by exstntlmsnthrp** [comment]
@farfromrefug I didn't say anything about obtanium. 

If the implications for you are so onerous, why not explain them to the public? Then maybe people might be a little more understanding. Otherwise it just looks like lazy development practices, because you can't be bothered.

**Comment by farfromrefug** [comment]
@exstntlmsnthrp Ok so github notifications yes you will get one for each cardwallet release. Maybe you can filter them i dont know.
Now about the implication it is easy:
* the 2 apps share 90% of the same code
* whenever i change something it is directly available to the other app
*  i need a lot less commits/merges which represents a lot of my time on a daily basis. And i am not paid to develop those apps (even if i am trying to live out of open source, but really far from it right now). I maintain around 60 open source repos which takes a lot of time. Every little gain is huge for me
* Issues are shared when reported (because of the common code) so it is good for me to have all in one place
* sidenote you can read everywhere on the web about the benefits of monorepos
* It is a lot more eco friendly, which is REALLY important for me. One repo means a lot less disk space usage (my repo quite big because if third parties i use like opencv/tesseract/zxing-cpp), a lot less bandwith usage. It also means that locally a lot of resources are built only once for both apps, which means less computing time => faster builds and less energy usage.

Will think about other benefits. But appart from the notification issue which appeared in this thread i dont see any other drawback. So i dont see any reason to change the way it is  right now

**Comment by exstntlmsnthrp** [comment]
@farfromrefug I'd just like to say thanks for taking your time to share this very thorough explanation. Much appreciated. 

I better understand where you're coming from and the decision you've made regarding this. 

Thank you.
