### ISSUE TITLE
[FEATURE REQUEST] button to add next photo

### ISSUE THREAD

**Issue by krzemyczek** [Akylas/OSS-DocumentScanner#237]
**Is your feature request related to a problem? Please describe.**
When I'm taking photo of the first page, if I want to add next one I have to return and then click the document at the top and then '+' button. 

**Describe the solution you'd like**
It would be easier if there was a button which allow you to add next photo without need of exit scanning.

**Describe alternatives you've considered**

**Additional context**
![Screenshot_20240617-090901_1](https://github.com/Akylas/OSS-DocumentScanner/assets/81762967/01b139d9-8c35-4a27-a601-b9719446d141)
(Button somewhere there)

**Comment by farfromrefug** [comment]
@krzemyczek thanks for the report. Did you try the batch mode from the camera view?
I understand your point but not sure it is needed to add another button on that view as i think batch scan is what you are looking for. But i might be wrong

**Comment by krzemyczek** [comment]
Wait. I didn't know about this; yes, this is exactly what I was thinking of, thanks a lot!
