### ISSUE TITLE
Please Separate the Apps

### ISSUE THREAD

**Issue by Scrat80** [Akylas/OSS-DocumentScanner#240]
### Version

Could you separate the apps so Obtanium doesn't overwrite one app with another? If there's a way to fix this in Obtanium, please make a guide.

Thanks!

### What platform are you using?

Android

### OS Version

Graphene OS, always updated.

### What happened?

Apps overwrite each other.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
It has already been https://github.com/Akylas/OSS-DocumentScanner/issues/232.
And there is now obtainium badges on readme so that you can add both apps separately
