### ISSUE TITLE
Mark  card wallet as FOSS

### ISSUE THREAD

**Issue by czarnyckm** [Akylas/OSS-DocumentScanner#242]
The Inure app manager shows card wallet as not FOSS. I think due to lack of the license.
The DocumentScanner is marked correctly as FOSS in the Inure app manager

**Comment by farfromrefug** [comment]
@czarnyckm did not know about inure. Not sure where it gets its data for app information.  I asked him https://github.com/Hamza417/Inure/discussions/349

**Comment by farfromrefug** [comment]
@czarnyckm so it seems there is nothing to do and it will eventually get marked as FOSS. Being on izzydroid is enough
