### ISSUE TITLE
[BUG] Untranslated strings show translation key

### ISSUE THREAD

**Issue by flipflop97** [Akylas/OSS-DocumentScanner#244]
### Version

Card Wallet 1.0.2 (build 4)

### What platform are you using?

Android

### OS Version

Oneplus 7T
Android 12

### What happened?

Untranslated strings show up as translation keys instead of using English as a fallback. See this example using Dutch:

![Screenshot_2024-06-21-09-38-03-87_2479e19a79dc1a445e01f91605b26938](https://github.com/Akylas/OSS-DocumentScanner/assets/13943260/98c29842-8aea-49d3-bec1-56745344d042)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@flipflop97 it is because dutch translation is not finished.
You can contribute here https://hosted.weblate.org/projects/oss-document-scanner/#languages

**Comment by flipflop97** [comment]
Yes I know, that translation came from me, I hope to finish it soon 😄

The issue is that the app will never always be fully translated in all languages, so there will always be some strings that are untranslated. Right now these strings show up as placeholders to users, meaning they can't read the text there at all. Pretty much all other apps solve this problem by falling back to the original/English string if a translation isn't found. This way users can still read what is being said, albeit in English (everything is in English anyway if a translation doesn't exist at all).

**Comment by farfromrefug** [comment]
@flipflop97 OK I understand . will see what I can do and try to add English fallback.

**Comment by farfromrefug** [comment]
@flipflop97 should now be fixed

**Comment by flipflop97** [comment]
Thanks!
