### ISSUE TITLE
[BUG] Stuck at capturing

### ISSUE THREAD

**Issue by cd-FileX** [Akylas/OSS-DocumentScanner#256]
### Version

1.7.1 build 71

### What platform are you using?

Android

### OS Version

Android 11 degoogled

### What happened?

When trying to scan the page below, the app is getting stuck in capturing. If switching the app and coming back, it is fully stuck without any movement.
![IMG_20240708_213523](https://github.com/Akylas/OSS-DocumentScanner/assets/79639219/d4833c13-3b59-4c4c-8f33-0138d685dd4c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@cd-FileX are you scanning by importing that image? or are you using the camera?
if you are using the camera, what are your settings? Like autoscan, batch mode ... 
Does it only happen when scanning this page? Or does the app always "hang" while scanning?

**Comment by farfromrefug** [comment]
@cd-FileX btw in your issue you mention 1.7.1 which is quite an old build. Could you try and upgrade to latest?
