### ISSUE TITLE
[FEATURE REQUEST] Export to WebDav-Folder

### ISSUE THREAD

**Issue by will2048** [Akylas/OSS-DocumentScanner#258]
**Related problem**
The actual implementation of WebDav-Sync creates folders, metadata and original files. To much if only PDF or image file needed.

**Solution I'd like**
Under Settings > PDF-Export > Export folder > Option to set a WebDav-Folder instead of local path on device.
So Export-Function for PDF and JPG/PNG can upload Files.

**Side note**
Because this export folder is used for PDF and JPG/PNG I suggest to rename "PDF-export" to "export" or "export settings", set the headline "PDF settings" under "export folder"  folllowed by the current settings there and at the end there should be the settings from "image settings" which current location ist "settings", parallel to "PDF export" (image format, image quality).

**Alternative I've considered**
#254 WebDav via File Explorer in Share-Button won't work.

**Additional context**
Export JPG/PNG here would upload processed file to previously selected WebDav-Folder.
![Screenshot_2024-07-04-22-06-07-16_95dcfb87bea3b5fbac634956b75eabe9](https://github.com/Akylas/OSS-DocumentScanner/assets/174485273/8c36bbc6-1db2-49cb-b7ce-c0bafc756a31)

Thank you very much!

**Comment by farfromrefug** [comment]
@will2048 there is a fully new sync system in latest version which allows you to sync PDF/images to WebDAV/local folders

**Comment by will2048** [comment]
I can't decide to call it fantastique or bombastique! 🥳

Thank you very much for your effort.

This Feature Request can be considered as implemented.
