### ISSUE TITLE
[FEATURE REQUEST] Material You icon in card wallet

### ISSUE THREAD

**Issue by SpiritOTHawk** [Akylas/OSS-DocumentScanner#259]
![Screenshot_20240712-110236](https://github.com/user-attachments/assets/eb196124-840b-4273-8f31-6b391b3e00b3)

**Comment by farfromrefug** [comment]
@SpiritOTHawk thanks i need to create a monochrome icon

**Comment by farfromrefug** [comment]
@SpiritOTHawk should be implemented in latest
