### ISSUE TITLE
Downloaded package ID does not match existing App ID

### ISSUE THREAD

**Issue by realAllonZ** [Akylas/OSS-DocumentScanner#264]
I received an update notification for OSS Document Scanner but when I tried to install I received the following error:

`Downloaded package ID does not match existing App ID - com.akylas.cardwallet [OSS Document Scanner]`

Is this error to be expected?

If so, uninstall then reinstall?

**Comment by farfromrefug** [comment]
@realAllonZ use the badges for obtainium on  repo readme to add updates for document scanner.
There are 2 apps hosted on this repo. You need a special filter

**Comment by farfromrefug** [comment]
@realAllonZ thanks i modified the readme to remove `matchGroupToUse` for Card Wallet. Hope it is going to work for others!
