### ISSUE TITLE
[BUG] Pages look changes with filters order

### ISSUE THREAD

**Issue by cd-FileX** [Akylas/OSS-DocumentScanner#277]
### Version

1.10.3 (91)

### What platform are you using?

Android

### OS Version

Miui 14.0.6 / Android 13

### What happened?

If for example applying in the order of Color > Enhance > Whitepaper, the image sometimes looks some weird at some places.
If applying in the order of Enhance > Whitepaper > Color, the image quality seems to be the best.

I don't think this should happen, but rather be applied in a specific (the best) order.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@cd-FileX The result really depends on the image itself. In some cases `Color > Enhance > Whitepaper` might be better than `Enhance > Whitepaper > Color` which is apply in the order your "select" them.
A lot of improvements can be made in the filters/transforms. I am still trying to find better algorithms to match other doc scan apps.
