### ISSUE TITLE
[FEATURE REQUEST] Undo image transformations

### ISSUE THREAD

**Issue by cd-FileX** [Akylas/OSS-DocumentScanner#278]
**Is your feature request related to a problem? Please describe.**
Image transformations are not undoable at once, but only for single pages. 

**Describe the solution you'd like**
A marker in the transform images dialog for the throughout selected option.

**Describe alternatives you've considered**
An undo button.

**Additional context**
Related to #279

**Comment by farfromrefug** [comment]
@cd-FileX nnot sure why this would be needed. You can already "unselect" transformations.
Maybe i am not understanding which transformations you are talking about

**Comment by farfromrefug** [comment]
@cd-FileX ok i see now. Not sure how an undo would work. Not easy to implement

**Comment by farfromrefug** [comment]
> I guess you would have to track which images were changed and what changes were made. Also, if there is not already one, you should save a config file or data of every image. Then you can take this data and mark the option in the multiple transformation dialogue. Else you could also just do it with a switch, so images which have the transformation but the switch is toggled off, get the transformation removed. The other way around if it is turned on the transformation in being added.

Yes i would have to track more history for image because of consecutive changes. I dont think it is worth it. Hope you understand

**Comment by farfromrefug** [comment]
@cd-FileX i dont sée what it would solve. There is never a case where an image is marked as transformed while not being transfromed, or the contrary. Even when it crashes!
I am.sorry i dont sée what the issue really is except from the crash. 
You can always untransform images by selecting transform images and do it with all unselected

**Comment by farfromrefug** [comment]
@cd-FileX you are right I could make it easier to understand

**Comment by farfromrefug** [comment]
@cd-FileX there is now a reset button so you know what you are doing
