### ISSUE TITLE
[FEATURE REQUEST] Possibility to share PDF files with OSS Wallet

### ISSUE THREAD

**Issue by cs-nero** [Akylas/OSS-DocumentScanner#280]
**Describe the solution you'd like**
I want to be able to share PDF files with the Wallet. The PDF will be imported then.
Is that possible?
See the screenshot attached
![Screenshot_2024-08-09-14-48-34-193_android_1](https://github.com/user-attachments/assets/3b895df9-3777-4eb0-b2e6-cc3d01af1554)

**Comment by farfromrefug** [comment]
@cs-nero it should already be possible. Will look at it when i am back. 
Thanks

**Comment by farfromrefug** [comment]
@cs-nero It is now released !

**Comment by cs-nero** [comment]
Works, nice! Thanks
