### ISSUE TITLE
sync old data after new installation

### ISSUE THREAD

**Issue by Himra** [Akylas/OSS-DocumentScanner#287]
### Version

1.10.4/92

### OS Version

Android 14

### What happened?

Hello

I have done the following.

I've been using the app together with Nextcloud for a while. Now I have a new smartphone and would like to use the previous data on Nextcloud in my app again. But unfortunately I get the message 
`TypeError: Cannot read properties of undefined (reading ‘path’)`

The synchronization worked for the most part. The data is available in the app's data folder, but unfortunately without the JSON file.

What can I do?

The smartphone does not allow a manual copy of the JSON file into the data folder

Thank you for your help

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RawmanGrey** [comment]
Same `data.json could not be located` here, Android 14 (Graphene OS), v.1.1.4 Build 14

**Comment by farfromrefug** [comment]
@RawmanGrey @Himra released a new version yesterday that should fix it
