### ISSUE TITLE
Moving the cropping markers slowly is broken

### ISSUE THREAD

**Issue by AlphaCraft9658** [Akylas/OSS-DocumentScanner#290]
### Version

1.10.5.94

### What platform are you using?

Android

### OS Version

OneUI 6.1

### What happened?

I tried making subtle adjustments to the corners and edges of a document in a scan, but the markers lag behind or don't move at all most of the time. This makes cropping a scan very difficult on my tablet, which is the main device I need to scan documents with.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@AlphaCraft9658 really sorry to hear that:
* what s your tablet? if i could reproduce that would be great.
* by any chance if you can create a video so i can see the lag that would help.

Will fix it

**Comment by AlphaCraft9658** [comment]
> @AlphaCraft9658 really sorry to hear that:
> * what s your tablet? if i could reproduce that would be great.
> * by any chance if you can create a video so i can see the lag that would help.
> 
> Will fix it

Actually, it seems to affect any device. I also tested it on my phone and the issue persists there as well. It not only affects subtle movements. The markers generally don't quite follow the finger. This is just especially noticeable when moving the finger slowly. Here is a demonstration video of the bug: https://youtu.be/hotm1Si2TQc

**Comment by farfromrefug** [comment]
Thanks for the vidéo i know clearly see the issue ! Will try to reproduce her and then fix it!

**Comment by farfromrefug** [comment]
@AlphaCraft9658 In fact i see the issue now. And it is not a bug but a feature. The sensitivity of the dragging has been lowered per users request. But in your case it might not be good.
You can increase it in settings/document_detection/magnifier_sensitivity. I ll change the description of the settings as it is not clear enough

**Comment by AlphaCraft9658** [comment]
> @AlphaCraft9658 In fact i see the issue now. And it is not a bug but a feature. The sensitivity of the dragging has been lowered per users request. But in your case it might not be good.
> You can increase it in settings/document_detection/magnifier_sensitivity. I ll change the description of the settings as it is not clear enough

Okay. But now I tested that, but it seems like max sensitivity doesn't fully solve my issue. It's still lagging behind a tiny bit when trying to do precise movements.

**Comment by farfromrefug** [comment]
@AlphaCraft9658 Will take a look again. Could be a rounding issue
