### ISSUE TITLE
[FEATURE REQUEST] Native app-wide landscape mode (dynamic)

### ISSUE THREAD

**Issue by AlphaCraft9658** [Akylas/OSS-DocumentScanner#293]
**Is your feature request related to a problem? Please describe.**
The app is less easy to navigate on a tablet, which is often used in landscape.

**Describe the solution you'd like**
An app-wide native landscape mode (dynamic)

**Describe alternatives you've considered**
Samsungs force-landscape, which is flawed sometimes just as it is here

**Comment by farfromrefug** [comment]
@AlphaCraft9658 what do you mean by app wide native landscape mode? Do you have a screenshot idea?

**Comment by AlphaCraft9658** [comment]
> @AlphaCraft9658 what do you mean by app wide native landscape mode? Do you have a screenshot idea?

The app can not be run in landscape mode by normal means. The only way I can do it right now is using the experimental Samsung Labs feature in OneUI which forces apps into landscape. It would be nice to have the app support landscape by itself.

**Comment by farfromrefug** [comment]
@AlphaCraft9658 indeed it cant ! will enable it.

**Comment by farfromrefug** [comment]
@AlphaCraft9658 just released a new version with landscape support
