### ISSUE TITLE
[FEATURE REQUEST] Add ability to rename scans

### ISSUE THREAD

**Issue by AlphaCraft9658** [Akylas/OSS-DocumentScanner#294]
**Is your feature request related to a problem? Please describe.**
It's hard to distinguish different scans just by date as it's not as descriptive of the content. It's just messy looking at the list of scans.

**Describe the solution you'd like**
When selecting a scan or opening it for editing, the Triple-Dorf menu in the top right corner should also have a rename option.

**Describe alternatives you've considered**
There aren't really any real alternatives.

**Additional context**
![Screenshot_20240926-071812_OSS Dokumentenscanner~2.png](https://github.com/user-attachments/assets/341c06dc-a61f-4813-b715-5bd7d6222df2)

**Comment by farfromrefug** [comment]
@AlphaCraft9658 
So when you talk about scan we muât try to figure out what you are talking about. 
In the app code in have the notion of  document and each document have pages. Which corresponds to the Ui of the app.
Is that document you are talking about ?

You can already rename documents. Simply click.on its name while viewing it. 
I can still add a menu entry as another mean of changing it

**Comment by AlphaCraft9658** [comment]
> @AlphaCraft9658 
> So when you talk about scan we muât try to figure out what you are talking about. 
> In the app code in have the notion of  document and each document have pages. Which corresponds to the Ui of the app.
> Is that document you are talking about ?
> 
> You can already rename documents. Simply click.on its name while viewing it. 
> I can still add a menu entry as another mean of changing it

I didn't know that this was possible already. Maybe you could add the menu entry and a visual indicator to the document name, like a pen, to indicate that you can rename it by tapping the name.

**Comment by farfromrefug** [comment]
It is now added in the ⁝ menu
