### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by NarwhalPrince** [Akylas/OSS-DocumentScanner#305]
## Add App Signer Certificate Hash for Document Scanner App

**Description**: 
Please add the app signer certificate hash for the document scanner app, making it compatible with AppVerifier. This would allow users to easily verify the app's integrity during testing and enhance security by ensuring that only the legitimate app is being tested.

Why

- Simplifies the validation process for people installing through Obtanium

- Ensures the authenticity of the app when used with AppVerifier.

Thanks!

**Comment by farfromrefug** [comment]
What is the app signer certificate ? Any documentation?

**Comment by NarwhalPrince** [comment]
APKs are signed with the developer's certificate. 

https://developer.android.com/studio/publish/app-signing


AppVerifier uses this to verify the authenticity of the APK.

https://github.com/soupslurpr/AppVerifier

**Comment by farfromrefug** [comment]
@NarwhalPrince OK sorry I misunderstood so you just want me to put my hash in the readme ?

**Comment by NarwhalPrince** [comment]
In the README works great. This helps a lot with downloading apps from sources without a chain of trust. 

Thank you!

**Comment by NarwhalPrince** [comment]
That looks good for the Play Store versions of both OSS Scanner and CardWallet. 

The IzzyOnDroid and GitHub versions report the following for OSS Scanner:

com.akylas.documentscanner
0D:10:AA:10:E0:3A:7E:76:97:22:BE:43:88:BE:63:BD:15:7A:7B:7B:F1:96:FB:3C:EB:AB:87:37:F9:6C:A8:71

And they report the same hash for CardWallet, as expected:

com.akylas.cardwallet
0D:10:AA:10:E0:3A:7E:76:97:22:BE:43:88:BE:63:BD:15:7A:7B:7B:F1:96:FB:3C:EB:AB:87:37:F9:6C:A8:71

**Comment by farfromrefug** [comment]
@NarwhalPrince this is strange. I got those from AppVerifier using the versions installed on my phone which are github versions. 
Not sure what s going on here

**Comment by NarwhalPrince** [comment]
The hashes you listed in the README correspond to the versions on Play Store according to my testing. Check your app info for the installation source?

**Comment by NarwhalPrince** [comment]
![Screenshot_20241009-085505.png](https://github.com/user-attachments/assets/7d0ec529-ed7d-4392-8e95-abb6c054d1f9)

![Screenshot_20241009-085559.png](https://github.com/user-attachments/assets/c5b3eaee-32d8-4d3c-aa97-0b6a63239103)

**Comment by farfromrefug** [comment]
@NarwhalPrince Thanks a lot must be an issue on my side. I updated with the hashes you provided!

**Comment by NarwhalPrince** [comment]
Awesome, thank you!
