### ISSUE TITLE
Weblate could not merge the repository.

### ISSUE THREAD

**Issue by stxm** [Akylas/OSS-DocumentScanner#31]
Hi @farfromrefug 

I wanted to add a new language translation during the holiday, but weblate seems to have a merge issue alert

See: https://hosted.weblate.org/projects/oss-document-scanner/application-strings/#alerts

kudos for the app!

**Comment by farfromrefug** [comment]
@stxm indeed seems like there is a merge issue. will try to fix tonight

**Comment by farfromrefug** [comment]
@stxm it is fixed
