### ISSUE TITLE
Fingerprint of apk signing certificate

### ISSUE THREAD

**Issue by rdy2go** [Akylas/OSS-DocumentScanner#316]
For users not compiling the apk themselfes and instead rely on provided builds (on Github) it would be good to provide a fingerprint as SHA256 from the signing certificate for the user to verify the apk.

**Comment by farfromrefug** [comment]
@rdy2go isnt it what you want https://github.com/Akylas/OSS-DocumentScanner?tab=readme-ov-file#appverifier-hashes ?

**Comment by rdy2go** [comment]
True. My Bad. I checked a few weeks ago and assumed that it was still not provided. But with a commit 2 weeks ago it got introduced. Thanks.
