### ISSUE TITLE
[FEATURE REQUEST] Default to Camera when opened

### ISSUE THREAD

**Issue by thisisartman** [Akylas/OSS-DocumentScanner#321]
**Is your feature request related to a problem? Please describe.**
When I open the app, it opens to the document list. 
This is an additional step that slows down my scanning. Because generally, I don't need to view my scans from the app. I can do so from the file explorer too. The one thing I do need to do is scan the document.

**Describe the solution you'd like**
Anytime I open OSS Document Scanner (maybe try a simpler name like DocScan?), it should open the camera view.

**Describe alternatives you've considered**
The alternative is to just press the Camera button once the app opens.

**Additional context**
I'm attaching two screen recordings showing the opening comparison between OSS Document Scanner and Microsoft Lens.
Microsoft Lens is first.

https://github.com/user-attachments/assets/a53f9819-13a3-4cf1-ab64-b92eb6df19a9

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by farfromrefug** [comment]
@thisisartman it is in fact already coded. Will finish it and publish it soon

**Comment by thisisartman** [comment]
> @thisisartman it is in fact already coded. Will finish it and publish it soon

Extremely excited to see what all you've been cooking for the next version 🥳

**Comment by farfromrefug** [comment]
@thisisartman i am about to release it. Just so you know in this version when enabling "start on cam", the camera becomes the main "page". So you dont close it to go to your document list, you use the top right icon to see the document view. Then if you go back you go back to the camera.
There would be another way which would be just to open the camera view on start. The app would then have the same workflow.

Not sure what you prefer, let me know.

**Comment by thisisartman** [comment]
> @thisisartman i am about to release it. Just so you know in this version when enabling "start on cam", the camera becomes the main "page". So you dont close it to go to your document list, you use the top right icon to see the document view. Then if you go back you go back to the camera.
> There would be another way which would be just to open the camera view on start. The app would then have the same workflow.
> 
> Not sure what you prefer, let me know.

This is essentially the way Office Lens does it and I am 100% comfortable with it.
But I do have a suggestion... If possible, can the document list button below somewhere near the bottom? Idk how exactly you would do this... I'll see if I can make a mockup for that later on.

For the time being, this is awesome. And thanks for being so active 🫡

**Comment by thisisartman** [comment]
> @thisisartman i see about the button let me see how i can do this. 

I've added some screenshots to give you an idea of what I mean above... I didn't realise I could just reply to it and edited the comment.

**Comment by thisisartman** [comment]
> @thisisartman nice. I see your point but that actually that "empty" space is used in batch mode to show the confirm button

Ah yes... Just tried it. For reference:
![Screenshot_20241107-195041_OSS Document Scanner.png](https://github.com/user-attachments/assets/316eb69b-56a8-4374-ac0f-31c3aaf4f2a0)

Okay, then maybe we could shift up the batch mode toggle to the toolbar above the shutter button?

![Screenshot_20241107-195145_OSS Document Scanner.png](https://github.com/user-attachments/assets/7c99eb7f-da16-448d-bf22-79855122d4b8)

It's anyway a simple toggle, so it's accessible, plus gives us the space required for the gallery/document list button.

Minor suggestion: Can we switch the icon for Batch Mode to be different? I'll create a separate issue with a suggestion in a bit... I'll whip up a mockup that'll be helpful. This is it for now, I promise 😂.

**Comment by thisisartman** [comment]
@farfromrefug the latest release says OSS Card Wallet. Are you sure you've pushed the right file?

**Comment by farfromrefug** [comment]
@thisisartman it is normal. I release 2 apps from this repo. Did not publish the document scanner yet ;)

**Comment by thisisartman** [comment]
> @thisisartman it is normal. I release 2 apps from this repo. Did not publish the document scanner yet ;)

Oh, okay.
It's a bit confusing since the release is under the name of OSS Document Scanner.
Is there any specific reason for why you chose to merge these two apps?

**Comment by farfromrefug** [comment]
@thisisartman indeed the repo is named after the DocumentScanner app. The reasoning is that 70% of the code is shared. And by having one repo it means i can develop/publish almost twice as fast.
BTW this repo actually published 4 apps because i publish iOS and Android apps. Seeing the complexity of it having one repo means it is really easier to maintain (like when i fix something i dont have to copy over to another repo... or 3 repos ...)

**Comment by farfromrefug** [comment]
@thisisartman it is now released!

**Comment by thisisartman** [comment]
> @thisisartman it is now released!

Been using it regularly! It is so much better now.

I have run into some things I'd like to suggest... I'm creating the issues as we speak.
