### ISSUE TITLE
[FEATURE REQUEST] Make borders snap to edges of scan in Editing mode.

### ISSUE THREAD

**Issue by thisisartman** [Akylas/OSS-DocumentScanner#322]
**Is your feature request related to a problem? Please describe.**
When editing a scan, the borders are very sluggish to drag and a bit difficult to move around to fit the shape of the document.

**Describe the solution you'd like**
Ability to drag the handles faster, and have them snap to the corners wherever possible to make it easier to get the document cropped.

**Describe alternatives you've considered**
The only other alternative I see as of now is to just make the handle dragging easier. Until we get the edge management sorted out.

**Additional context**
A comparison between how OSS Document Scanner handles editing vs how Microsoft Lens handles it.

MS Lens:
https://github.com/user-attachments/assets/6da2a14b-be72-4016-b153-5ae9a47e731a

OSS Document Scanner:
https://github.com/user-attachments/assets/a746c928-24f1-4c52-b561-88df3fafc491

**Comment by farfromrefug** [comment]
@thisisartman thanks for the report. 
What MSLens does is really nice thought i dont really know how they do that .

Now about the real issue here which is the sluggishness. It is really obvious in your video. Though i cant reproduce it here.
What s your phone/android version?
can you share the image you are testing with?

**Comment by thisisartman** [comment]
> What s your phone/android version?

My bad. I forgot to mention this.
Crdroid 10.9 (Android 14) custom ROM on a Poco F4 5G.

**Comment by farfromrefug** [comment]
@thisisartman thanks. I figured it out. It is not really sluggishness. It happens when the "corners" are too close the view borders. Then it keeps on "blocking". If you move the corners a bit out of the borders, it should not be sluggish anymore.
Will try to fix it

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by farfromrefug** [comment]
@thisisartman can you try latest version and tell if it is better?

**Comment by thisisartman** [comment]
> @thisisartman can you try latest version and tell if it is better?

I just tested it. It seems to be solved.
Awesome work! Thanks alot!
