### ISSUE TITLE
[BUG] QR Code disappeared after installing new app version

### ISSUE THREAD

**Issue by big-ant** [Akylas/OSS-DocumentScanner#329]
### Version

1.3.0 Build 20

### What platform are you using?

Android

### OS Version

Android 15 on GrapheneOS 

### What happened?

QR Code is no longer visible, just the text of the barcode is there when clicking on a card, no change after re-generating the code

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by big-ant** [comment]
QR Code on card is in 'Data Matrix' format

**Comment by farfromrefug** [comment]
@big-ant really sorry about that. Will fix tomorrow. Thanks for letting me know

**Comment by farfromrefug** [comment]
@big-ant i tried and could not reproduce. What changed is that now if there is no qrcode (whatever the format) the layout is different. It will go back to the "qrcode" layout once a code is added.
Can you share a screenshot maybe of the issue you are facing?

**Comment by big-ant** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/c4f3d09a-794d-4b41-97ff-6f6efdbb0aaa)

![Screenshot_2](https://github.com/user-attachments/assets/59870939-359d-4efd-82b3-834ba3fddb1a)

![Screenshot_3](https://github.com/user-attachments/assets/ab702979-b5a9-45b1-9a91-be764e05bddc)

![Screenshot_4](https://github.com/user-attachments/assets/39b99fd2-c506-41de-a7cb-0ff9f05743e0)

Screenshot 1+2 same card, and screenshot 3+4 another card

**Comment by farfromrefug** [comment]
@big-ant ok very strange. You dont see them either when NOT in dark mode?
Will try to reproduce

**Comment by big-ant** [comment]
Yes, same in normal mode. I did reinstall the app without success.

**Comment by sarimak** [comment]
I use latest LineageOS 21/Android 14 and upgraded the app from F-Droid (Izzy on Droid repo) and barcodes/QRcodes disappeared as well. I see only the alphanumeric string at the bottom of the screen with white background. Version 1.3.0.20

**Comment by farfromrefug** [comment]
@sarimak @big-ant reproduced it! i am on it

**Comment by Uz4ever** [comment]
Sale problem here.

Matrixx OS - Android 14
App ver. 1.3.0.20

All barcodes disappeared
![Screenshot_20241109-163401_OSS Portafoglio Carte](https://github.com/user-attachments/assets/288b8949-f871-4f29-83fd-35d9e3745932)

**Comment by farfromrefug** [comment]
@sarimak @big-ant @Uz4ever new version up on github  with a fix

**Comment by sarimak** [comment]
Installed the released APK and the barcodes and QR codes work now. Thank you for the fix! ❤️

**Comment by big-ant** [comment]
Can confirm that it works again! Thank you.

Btw I had once this error while scanning a new card, but card was added and it worked anyway.
![IMG_20241109_230602](https://github.com/user-attachments/assets/f3a1210b-c504-4a17-8152-6aa2dd45288c)

Cheers, Roman

**Comment by farfromrefug** [comment]
@big-ant I had report of this one but could not reproduce again. Any chance you can share a video ?

**Comment by CyberMinion** [comment]
The update worked here as well.

Thank you!

**Comment by big-ant** [comment]
> @big-ant I had report of this one but could not reproduce again. Any chance you can share a video ?

No chance to reproduce this issue so far. It happened when scanning a card where you could see the outline of the scan in violet filling up ... You did implement a different method by now?

I think we can close this ticket as the issue with the barcodes seems to be resolved. Thank you for your quick responses! Awesome app!
