### ISSUE TITLE
[BUG] Sharing does not use current version of image

### ISSUE THREAD

**Issue by SammysHP** [Akylas/OSS-DocumentScanner#336]
### Version

1.12.3 Build 103

### What platform are you using?

Android

### OS Version

Android 14

### Steps

1. Open document scanner
2. Take photo of document
3. Edit photo (brightness, contrast)
4. Tap on "share" and then on "share" again

### Actual result

Original photo is shared.

### Expected result

Currently visible version is shared.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@SammysHP thanks for the report. I tried to reproduce but it worked fine here. Any change you can share a video?

**Comment by SammysHP** [comment]
https://github.com/user-attachments/assets/ebdc6cb2-86a3-445f-9ec7-20e3a364bec7

**Comment by farfromrefug** [comment]
@SammysHP thanks for the video. May i ask what s the app you shared too? It seems to be a message app. But which one? I am interested by the fact it first proposes to edit the image

**Comment by SammysHP** [comment]
> May i ask what s the app you shared too? It seems to be a message app. But which one? I am interested by the fact it first proposes to edit the image

That's Signal, but I guess WhatsApp behaves similar.

> EDIT: fixed! will be in next version. Thank you for the report!

Thanks!

**Comment by farfromrefug** [comment]
@SammysHP It is released ! (soon on PLay store)
