### ISSUE TITLE
Cannot import PDF on iOS 18.1

### ISSUE THREAD

**Issue by thaihugo** [Akylas/OSS-DocumentScanner#374]
### Which app is your issue for

CardWallet

### Version

1.5.3 build 25

### What platform are you using?

iOS

### OS Version

18.1

### What happened?

Hi,

when I try to import a PDF boarding pass from my files into card wallet, I get the message in the attached picture. On android, the same file will work without error. No PDF file I have can import.
![IMG_0691](https://github.com/user-attachments/assets/c93d036c-71d4-4172-ae91-de2decefae3f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@thaihugo thanks a lot for the report. The issue is fixed and a new version is on the way

**Comment by thaihugo** [comment]
This is now working great! Thanks a lot for the quick fix.
