### ISSUE TITLE
Out of focus images - "wrong" camera used by default

### ISSUE THREAD

**Issue by S-Joao-V** [Akylas/OSS-DocumentScanner#43]
Hello!

Great app so far, Ive following it to replace onedrive's doc scan feature.

I'm archiving low value handwritten notes and noticed the following:
- When the viewfinder is open, there is a significant "fish eye" effect in the page being scanned
- After taking the shot, the overall image is relatively out of focus

What I tried:
- Taking a picture in the default camera app, in the same conditions, with all "scene optimizations" disabled = The result was way better with the written word being well defined across a whole A4 page
- The "1x" camera is used

What I noticed:
The default camera used in the scan viewfinder is the "0.6x" zoom one (as in the default camera app).
Zooming in in the scan viewfinder, the '1x' camera is used, the fish eye effect is not there, and checked by covering the cameras individually.
Can something be done to use the '1x' cam by default?

Obs:
When the '1x' camera was used the edge detection and preview worked as expected, but the image was not automatically saved, selecting the checkmark to save resulted in app crash, let me know if this should be a separated issue.

Build used:
v1.2.7 Build 17 from Izzydroid repo

Smartphone used:
Base Samsung S23 - Android 14 - One UI 6.0

**Comment by S-Joao-V** [comment]
In my now-backup phone Samsung S20FE - Android 13, by default the middle camera '1x' zoom is used in the app.

**Comment by farfromrefug** [comment]
@S-Joao-V hard to say what s going on. i checked and I let androidx/camera choose the default camera. not sure what I can do. can you try grapheneos/camera to see if it picks up the correct camera?
if it does I can compare the code

**Comment by S-Joao-V** [comment]
Hi @farfromrefug 
Ok, just tried the following apps:
https://f-droid.org/packages/net.sourceforge.opencamera
https://f-droid.org/packages/com.simplemobiletools.camera
https://apt.izzysoft.de/fdroid/index/apk/com.littletrickster.scanner
https://play.google.com/store/apps/details?id=app.grapheneos.camera.play

The 1x - middle - camera was the default one in all cases, even allowing the zoom out to 0.6x camera for the camera apps.

**Comment by farfromrefug** [comment]
@S-Joao-V OK good news. will see what I can do. BTW did you try changing 16:9/4:3?

**Comment by S-Joao-V** [comment]
@farfromrefug  same results, changing the aspect ratio, saving, reopening the app, initial camera is the 0.6x one.

**Comment by farfromrefug** [comment]
@S-Joao-V ok really strange. TBH it wont be easy to fix as i dont have a phone to reproduce your issue. Will still try

**Comment by S-Joao-V** [comment]
@farfromrefug  I've been using the batch button from the camera view to scan multiple pages, in this view the applied zoom is saved between pictures taken so not so much of an issue right now.

Had this idea: to have a default zoom setting that would be retained even for new documents. 
Apart from this issue, it could be useable for someone using a scanning stand/fixture (eg https://images-na.ssl-images-amazon.com/images/I/71cAwpy-T-L._AC_SL1500_.jpg, this one looks to be very adjustable but I made some makeshift ones in the past), where the right zoom would not change between documents scanned.

**Comment by farfromrefug** [comment]
@S-Joao-V good idea will see about saving the zoom (might be an option to enable zoom saving as it could be disturbing for users not expecting it)

**Comment by farfromrefug** [comment]
@S-Joao-V i just released 1.4.2. In this version you can set the camera resolution/aspectRatio. I hope this will enforce one camera or the other. Can you try?

**Comment by S-Joao-V** [comment]
@farfromrefug  thanks for the news
With build 1.4.2 build 43 I noticed two things, with testing focused on this report:

Changing resolution to all values in the dropdown still used the zoom out lens, the pictures taken does have the selected dimensions, by testing with the lowest available value.

The good news that I noticed while playing with the above settings:
- Open the viewfinder (default settings)
- Check the camera used = Zoom out one
- Press the power button, lock the phone
- Unlock the phone
- Check the camera used = 1.0x one is now being used by the viewfinder
I rolled back randomly to 1.2.24  build 34 and the same "workaround" worked too.

**Comment by farfromrefug** [comment]
@S-Joao-V @juniorcaesar very strange :D I am sorry it is hard for me to test as i cant reproduce the issue. 
will investigate more

**Comment by sverit** [comment]
> @farfromrefug thanks for the news With build 1.4.2 build 43 I noticed two things, with testing focused on this report:
> 
> Changing resolution to all values in the dropdown still used the zoom out lens, the pictures taken does have the selected dimensions, by testing with the lowest available value.
> 
> The good news that I noticed while playing with the above settings:
> 
>     * Open the viewfinder (default settings)
> 
>     * Check the camera used = Zoom out one
> 
>     * Press the power button, lock the phone
> 
>     * Unlock the phone
> 
>     * Check the camera used = 1.0x one is now being used by the viewfinder
>       I rolled back randomly to 1.2.24  build 34 and the same "workaround" worked too.

I have the same reported issue with my S23 Ultra (it uses the 0.6x wide lens), and I too can confirm this crude workaround works ;) The problem is, that I have to do this routine again for every new document I scan, which is kinda unpractical :/

Greath app otherwise, thank you for a decent local OCR pdf scanner <3

**Comment by farfromrefug** [comment]
@S-Joao-V @sverit sorry for replying late.
it is hard for me debug this as I dont had a phone where the issue happens
I believe it is an androidx camera issue. 
but not sure .
will try to think of a workaround

**Comment by sverit** [comment]
> @S-Joao-V @sverit sorry for replying late. it is hard for me debug this as I dont had a phone where the issue happens I believe it is an androidx camera issue. but not sure . will try to think of a workaround

Very understandable, no worries :)
Yeah, it looks like CameraX can only choose "front/rear camera". Camera2 seems to have a multi-camera-api to select a specific camera on Android 9 and above: https://developer.android.com/media/camera/camera2/multi-camera

**Comment by farfromrefug** [comment]
@sverit i think i fixed it! It was a zoom issue. By default my code was trying to set zoom to 0... which meant using the lowest zoom possible which in your case meant switching to the wrong camera!
I am going to release a version which default to 1.0 but also save and reuse the last zoom you used.

**Comment by farfromrefug** [comment]
@sverit @S-Joao-V new release is out. let me know if it fixes it

**Comment by S-Joao-V** [comment]
@farfromrefug  all good with v1.4.15 Build 56! Amazing.

**Comment by sverit** [comment]
> @sverit @S-Joao-V new release is out. let me know if it fixes it

Wow, that was fast! Works perfectly fine, thank you so much, great work! :)
