### ISSUE TITLE
Feature Request: Zoom in lens when selecting border points

### ISSUE THREAD

**Issue by iDazai** [Akylas/OSS-DocumentScanner#61]
In Microsoft PDF Lens there is the feature where if you want to rearrange the border points of the scanned document, you get a little zoomed in circle of where to put the border point. With that you don't have to look below your finger where it touches the screen. This would make rearraging the border points way easier. If you don't know what I mean with that, I'll get a screenshot of this feature.

**Comment by farfromrefug** [comment]
@iDazai There is already such feature. Might not work like Microsoft lens exactly but does the same job. It works like genius scan. Try moving corners and let me know what you think

**Comment by iDazai** [comment]
You are right, there's already a feature. I didn't see that at all. Maybe that's because my whole finger is covering this zoom circle. Maybe you could try to display this zoom circle above the point where the document/display is being touched?

**Comment by farfromrefug** [comment]
@iDazai there are multiple ways to look' at this. 
* yes I could put the lens somewhere else. 
* you dont need to touch on the corner. you can touch next to it. I grab the closest one. 
I think the second approach is better on a sense that once you knoz it feels more fluid (you don't need to be precise). the drawback is that at first you dont know about it ;). might need to add some "help/guide"

**Comment by iDazai** [comment]
Ah okay now I see it. Yeah, for me that wasn't intuitive. But good that this function is there. Maybe a little help instruction somewhere would help people like me.

**Comment by phigjm** [comment]
Thank you, I also didn't see the rearranging feature right away. It worked for me as soon as i pressed and held the number. Maybe an improvement would also be to make the entire page "draggable" instead of only the small number.

If I hold the entire page for a longer time it goes into a selection mode. But dragging doesn't do anything at the moment.

**Comment by farfromrefug** [comment]
@phigjm having 2 behaviors on long press is not something we usually do as it might lead to unexpected behavior. Usually apps add a drag "handle" on the side of the view. Though in my current design i dont really like it. I might have a idea about detecting a drag gesture and start the dragging from there. Though i would need to test that.
Will think about it.
@phigjm do you have issue with wrong page order after scan?

**Comment by phigjm** [comment]
@wrong page order:
well yes, I do have some issues:
https://github.com/Akylas/OSS-DocumentScanner/assets/39876427/79178675-0cdd-4650-a2f8-38dd98670a85

**Comment by phigjm** [comment]
When recording with Camea it (now) goes after each image directly into edit mode...

**Comment by farfromrefug** [comment]
@phigjm thanks a lot for the video! issue found and fixed!
