### ISSUE TITLE
App crashes on Android 7

### ISSUE THREAD

**Issue by MetehanOzyurek** [Akylas/OSS-DocumentScanner#69]
After I scan a photo it tries to compute and then crashes.

OS: Android 7.0
Device: SM-G920FQ

**Comment by farfromrefug** [comment]
@MetehanOzyurek what version have you installed?

**Comment by MetehanOzyurek** [comment]
> @MetehanOzyurek what version have you installed?

@farfromrefug 1.2.16.26 from F-Droid

**Comment by farfromrefug** [comment]
@MetehanOzyurek thanks i ll try to reproduce and fix as soon as possible

**Comment by farfromrefug** [comment]
@MetehanOzyurek i tried to reproduce on an android 7 device and could not reproduce your crash.
can you try with this build https://github.com/Akylas/com.akylas.documentscanner/releases/tag/test_android ?
once you got the crash, restart the app and i should receive a bug report
Thanks

**Comment by MetehanOzyurek** [comment]
> once you got the crash, restart the app and i should receive a bug report
> Thanks

I've installed and after confirming to crop the photo it crashed again. But when I try to restart the app, it crashes directly. I hope it was able to send the necessary log files.

**Comment by farfromrefug** [comment]
@MetehanOzyurek i am really sorry but i think my server was off when you tried :s Could you try again? maybe even trying to open the app again might send the bug report. Will tell you if i receive it

**Comment by MetehanOzyurek** [comment]
> @MetehanOzyurek i am really sorry but i think my server was off when you tried :s Could you try again? maybe even trying to open the app again might send the bug report. Will tell you if i receive it

No problem😅 I've cleared app data and tried to reproduce the crash - and restarted the app.

**Comment by farfromrefug** [comment]
@MetehanOzyurek got your crashes! will try to fix those

**Comment by MetehanOzyurek** [comment]
> @MetehanOzyurek got your crashes! will try to fix those

Great, thx so much👍

**Comment by farfromrefug** [comment]
@MetehanOzyurek ok so i might have fixed it. Though i see 2 errors in your logs, one i am no sure about. Can you download again from https://github.com/Akylas/com.akylas.documentscanner/releases/tag/test_android  and test ?
Thanks a lot for taking the time to test this!

**Comment by farfromrefug** [comment]
@MetehanOzyurek great! got your second crash. will try to fix it

**Comment by farfromrefug** [comment]
@MetehanOzyurek actually not sure i had the right crash log. Is it still crashing on editing the image? If so can you detail what you are doing? even maybe a video

**Comment by MetehanOzyurek** [comment]
> @MetehanOzyurek actually not sure i had the right crash log. Is it still crashing on editing the image? If so can you detail what you are doing? even maybe a video
> 
@farfromrefug No it didn't crash. I think it wasn't an important bug. So problem is solved for me, thank you so much.
