### ISSUE TITLE
[Feature Request] OCR whole document

### ISSUE THREAD

**Issue by phigjm** [Akylas/OSS-DocumentScanner#72]
At the moment I need to OCR process each page individually and need to wait shortly for each page.

Sugguestion:
I think it would be more convenient to apply the filter or OCR to the entire document at once instead of only applying it to a single page. 

Wish: 
At the best this would be done in the background, and I could continue scanning the next document.

**Comment by farfromrefug** [comment]
@phigjm good idea. I will try to add that soon

**Comment by farfromrefug** [comment]
@phigjm it has been released in the latest version on github!

**Comment by phigjm** [comment]
A little Beauty problem:
during the OCR: the Filter Bar is not really visible:

![image](https://github.com/Akylas/OSS-DocumentScanner/assets/39876427/967be1e1-f23f-4604-a794-4d699b33099a)

This might could maybe be fixed by moving the progress message up or only adding a progress bar close to the OCR [T] Icon.


Also: it would be awesome to apply the Filter and Enhancement central for the entire document as well (similar to the OCR function).

But apart from that: solid work. Thank you so much

**Comment by farfromrefug** [comment]
@phigjm yes it is the issue with snackbar. They kind of always are on top of something else :s Will think about it. Can you create an issue for the filter/enhancement apply to a whole document?
thanks
