### ISSUE TITLE
Option to remove white border / margin

### ISSUE THREAD

**Issue by meichthys** [Akylas/OSS-DocumentScanner#73]
Currently when exporting a PDF there is a large white border around the original scaned document. In my opinion this is usually not necessary since most documents that I am scanning already have a margin around the text.

![ResizedImage_Screenshot_20240109-080441.png_2024-01-09_08-06-51_1722.jpg](https://github.com/Akylas/com.akylas.documentscanner/assets/10717998/f52d1152-d8ba-490c-a10e-1a287204beb5)

**Comment by farfromrefug** [comment]
@meichthys Instead of doing directly export. do "preview" then use he chevron to change export settings. Those settings are saved for next export.
You can use page format to switch from a4 to full (pdf page size will be image size)
You can also change the page padding
