### ISSUE TITLE
[Feature Request] Add option to share PDF after scanning

### ISSUE THREAD

**Issue by graves501** [Akylas/OSS-DocumentScanner#74]
Hi, 

first of all thank you for this project. It's amazing! 

I just started out with using Paperless for all my paper documents. I use your lovely app to scan the documents and then upload it to Paperless.

Currently the workflow is:
1. Scan document
2. Export (= save) the PDF to Downloads
3. Open file manager
4. Upload scanned PDF via file manager to Paperless

So the option to export to another application would save quite a bit of work.
Also it might be useful to allow the user where to save the exported PDF.

Thank you for considering this feature :)

**Comment by farfromrefug** [comment]
@graves501 thanks a lot for the kind words. I didn't had share for pdf because the open would open in a PDF viewer where you could share.
but I see that in your workflow it would be better to share directly so I LL add it.

I use paperless too. I wanted to add sync feature to paperless (NGC) but their API dont support what I want (syncing already existing document when I add pages) and they dont seem really open to changes :(

**Comment by graves501** [comment]
@farfromrefug 

Thank you so much for considering! 
I guess adding a "Share PDF" functionality will be useful for other people as well. And it adds some consistency to the UX since the user can share the JPG/photo at the moment, but not the PDF version of the scan :thinking: 

That's interesting, can you send me a link to your proposal/Github issue? I'm just curious how the interaction went :thinking: 

Have a nice day :)

**Comment by farfromrefug** [comment]
@graves501 i added it in latest version ;)

**Comment by graves501** [comment]
@farfromrefug That's awesome, thank you so much! I tried it out and tried to share/send the PDF to "Paperless Mobile" but it doesn't seem like it's listed.

So I don't know why my phone (Pixel 7 Pro, Android 14, GrapheneOS) doesn't list Paperless Mobile in this context, because it does show up when I share it from e.g. the file explorer 🤔 Any ideas?

**Comment by farfromrefug** [comment]
@graves501 i got an idea. will try

**Comment by farfromrefug** [comment]
@graves501 new version up. I tested it with paperless and it worked

**Comment by graves501** [comment]
@farfromrefug Awesome! Can confirm, with version v1.2.24 it's working! Thank you so much, makes life easier :)

I think this issue can be closed now :)
