### ISSUE TITLE
Split multiline OCR text with newlines

### ISSUE THREAD

**Issue by balporig** [Akylas/OSS-DocumentScanner#75]
Better recognition of newlines in multiline document / image. Currently, most of the time multiple lines are merged into a single string without separator (space/newline). This relates to the text only OCR view

For reference, https://github.com/SubhamTyagi/android-ocr also uses tesseract as OCR engine and the newline detection is significantly more accurate, maybe some preprocessing or filters can be borrowed from there

**Comment by farfromrefug** [comment]
@balporig yes it was done on purpose because there was far too many unwanted new lines. Will find a better way

**Comment by farfromrefug** [comment]
@balporig new build released on github.
