### ISSUE TITLE
Copy button for OCR text

### ISSUE THREAD

**Issue by balporig** [Akylas/OSS-DocumentScanner#76]
Add a button to copy the whole text recognized by OCR, ideally with newlines #75

**Comment by farfromrefug** [comment]
@balporig good idea

**Comment by farfromrefug** [comment]
@balporig new build released on github. You can copy from the OCR data view. You can also long press on the button to show OCR data to quickly copy it

**Comment by farfromrefug** [comment]
@balporig  sorry about that. new build is up!

**Comment by farfromrefug** [comment]
there is already on  android 13 but you are right I LL add one on older android

**Comment by farfromrefug** [comment]
@balporig the visual confirmation has been added. Thanks for mentioning it
