### ISSUE TITLE
Db corruption?

### ISSUE THREAD

**Issue by juanjgit** [Akylas/OSS-DocumentScanner#79]
Hi
I lost all my scanned docments. Also, when I try to scan a new one the green tick button does nothing. And of I try to add from the gallery a popup with an error message about the database apperars.

![Screenshot_20240112-201134](https://github.com/Akylas/OSS-DocumentScanner/assets/3613326/159a8d37-3adb-4665-9a03-0d835e4ceaa4)

**Comment by farfromrefug** [comment]
@juanjgit sorry to hear that
did you du something special for this to happen ?
about the the sync tick you have WebDAV setup ?
that error I weird. it is like if your db had been erased

**Comment by juanjgit** [comment]
> @juanjgit sorry to hear that did you du something special for this to happen ? about the the sync tick you have WebDAV setup ? that error I weird. it is like if your db had been erased

I added a new sd card. But the data in in the internal memory, so it should not affect at all. I had not setup WebDAV yet. I guess I can remover the scanned images from /Android/data

The db seems to be there... I managed to open the sqllite file. 

![Uploading Screenshot_20240114-174717_1.jpg…]()

**Comment by farfromrefug** [comment]
actually yes it explains it. the data of the app is on the Edvard when possible. it was in your case. you did not loose anything. all is in your old sdcard under Android

**Comment by farfromrefug** [comment]
@juanjgit ok get it. But same thing:
* before: no sdcard => data written in internal
* sdcard added => app now writes on the sdcard and starts from 0. 
You can copy the data from your internal in Android/data/com.akylas.documentscanner/files to the same folder on the sdcard. Now your data will always be on your sdcard

**Comment by juanjgit** [comment]
That is what I tried, but it does not work. Along with the data, you copy the  db.sqlite database. In the "Page" table, the `ImagePath` column makes reference to the path `/storage/emulated/0/Android/data/` (internal memory). But the images are now at `/storage/4A21-0000/Android` (sdcard). If I had kept the data in the internal memory (no reinstall) it could have worked. Old documents would be in the internal memory and the new ones in the sdcard. But this is quite nasty.  Anyway, not everybody has a root explorer to be able to do these file movements and apply the workaround. 

I would suggest this fix. I don't know it it is possible. I would make a PR but I have 0 developer skills in Android :-)
- If there is sdcard: check if the [sdcard]/Android/com.akylas.documentscanner exists
- If it does not exist, copy data from  [intrernal]/Adroid/ and search and replace path names in Page.ImagePath
- Remove data from [internal]/Android

Workaround: use a root explorer to copy (not move) data from internal to sdcard

**Comment by farfromrefug** [comment]
@juanjgit indeed you are right didnt think of that. I dont think i can easily fix your case. What i think i ll do for future user:
* detect if sdcard : store where we write data (memory or sdcard).
* stick to that even if you change sdcard or add one
* maybe allow to change and move data. But for that i must make so that the db does not store full path but path relative to the location stored for all data. What bugs me is the migration needed for everyone to change paths.

Are you ok with that? And thank you for the kind words!

**Comment by juanjgit** [comment]
@farfromrefug Your solution will prevent this bug to happen again, so it is a good fix! You can always implement in the future a setting to select the storage device, But as you say, it would require a migration process that might now worth the time if there is no demand for the feature.

Thank you for your offer to fix my particular issue, but I already solved it by recreating the documents from scratch. I had access to the original images so I re-imported and them and ran the OCR. It was a tiny 15 register database. From now on I will setup a WebDaV sync  ;-)

**Comment by farfromrefug** [comment]
@juanjgit sorry you had to create all again :s I did implement it right now with the migration (was actually quite easy). I just need to implement the "move" feature. But this feature can come later.
Sorry again ...

**Comment by farfromrefug** [comment]
@juanjgit might not be of interest to you anymore but i published a new version right now which does the migration and then allow to move data between sdcard/internal.
I ll close this issue
