### ISSUE TITLE
Bug: no response adding photos from library when a batch of pictures are created

### ISSUE THREAD

**Issue by hammerfunctor** [Akylas/OSS-DocumentScanner#83]
On android-fdroid, when a batch of pictures is created, either from my photo library or from camera, I cannot add more photos from library. To reproduce it, simply press plus icon near the right bottom corner, then press the picture icon in the active camera stage. Nothing happens after that.

**Comment by farfromrefug** [comment]
@hammerfunctor if i understand correctly once you successfully imported images using the "+" the interface is not "reactive" anymore?

**Comment by hammerfunctor** [comment]
Exactly.

**Comment by farfromrefug** [comment]
@hammerfunctor thanks i ll fix it ASAP

**Comment by farfromrefug** [comment]
@hammerfunctor sadly i cant reproduce your error. Can you provide details:

* App version
* OS and version
* language

**Comment by hammerfunctor** [comment]
It turns out to be a permission issue. In the first startup I disallow the access to all my files and grant only access to media files. Reset the permission, and the problem is gone.

**Comment by farfromrefug** [comment]
@hammerfunctor i also tried what you mentioned and only grant access to media files, still could not reproduce your issue

**Comment by hammerfunctor** [comment]
Here is a demo
[screen.webm](https://github.com/Akylas/OSS-DocumentScanner/assets/65394269/b127064b-7700-47e9-8149-87240d0db610)

**Comment by farfromrefug** [comment]
@hammerfunctor awesome i reproduced the issue will fix!

**Comment by hammerfunctor** [comment]
Thanks!
