### ISSUE TITLE
Export and Share with Document Title

### ISSUE THREAD

**Issue by hoergen** [Akylas/OSS-DocumentScanner#84]
Since you can name your documents, it would be very helpful avoiding additional work that those titles are used with exporting/sharing the document as pdf.
Currently there are just generated document titles?

**Comment by farfromrefug** [comment]
@hoergen great idea! Will do that

**Comment by farfromrefug** [comment]
@hoergen it has been added

**Comment by hoergen** [comment]
Wow you are quick! Thank you very much.  :heart: 

I close this feature request.
