### ISSUE TITLE
Applying Filters to multiple pages at once

### ISSUE THREAD

**Issue by arnav-kr** [Akylas/OSS-DocumentScanner#86]
In normal usage, when we have to apply filters we generally apply filters to the whole document, say i want to invert colors to make it dark mode, currently i don't see an option to apply filters to multiple pages at once, or maybe i just couldn't find it, let me know if there already exists a thing,

For short document its not of a big deal to manually iterate over all of them and apply filters, but for big ones would be a lot of work.

**Comment by farfromrefug** [comment]
@arnav-kr it has been added in latest version

**Comment by arnav-kr** [comment]
> @arnav-kr it has been added in latest version

woah nice, that was quick 🫡
