### ISSUE TITLE
[BUG] Export setting `black_white` mess up image filter `Whitepaper`

### ISSUE THREAD

**Issue by hammerfunctor** [Akylas/OSS-DocumentScanner#88]
### Version

1.2.26.36

### OS Version

Android 14

### What happened?

1. Select filter `Whitepaper` in image processing 
2. Export -> Preview
3. Color -> black_white / color

`color` produces better output here while `black_white` seems to mess up the filter `Whitepaper`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@hammerfunctor i dont really understand what you are trying to say. I have tested and i dont see what could be wrong

**Comment by hammerfunctor** [comment]
Take [this](http://oracle.fengfubuffalo.tk:8080/test.tar.gz) tarball. The jpg file is the image I use, and `bw.pdf` and `color.pdf` are the outputs.

**Comment by hammerfunctor** [comment]
Keeping `Whitepaper` toggled on, in the preview stage whether `Color` is set to `color` or `black_white` produces documents of different quality, as I said above.

**Comment by farfromrefug** [comment]
@hammerfunctor i have looked at your images and tested and i dont see an issue with whitepaper combined with BW/Color mode from preview.
It does what it is supposed to do.  Yes BW does render differently than color because this is what BW does.
If you want to understand try to apply BW while editing a page (not through preview). You can longpress the BW filter to be able to change the BW "level". You'll what it does. Right now you cant change the "level" in the preview (but it is the same algo).

**Comment by hammerfunctor** [comment]
@farfromrefug Thanks for your comprehensive reply. So what kind of tasks is BW in the preview supposed to do?

**Comment by farfromrefug** [comment]
it make all images BW. but the way the BW algorithm works and with the défaut level it is at then it also "simplifies" to get more of a true black and white (and not gray level)

**Comment by farfromrefug** [comment]
@hammerfunctor thanks for closing this. but are you OK with the current app behavior ? 
me explaining how it works does not mean in am not up Tongan ri for the better of everyone

**Comment by hammerfunctor** [comment]
I'm genuinely satisfied this app appreciate for your work. Without such an convenient tool at hand, I either have a macrosoft spy lens sitting inside my phone, or reach to the printer in school before midnight homework deadline :| I had also attempted some simple sampling implementations on document scanner, but got too busy to figure out the bad behavior for specific image. So as a user of such a non-profit software, I really can't expect too much. I'm okay with the behavior for now, but I do think it's more natural to replace the functionality of `BW in preview' by an option to apply a filter to all images in processing. It's kinda misleading to me why I need to choose BW twice. Thanks once again, it's up to you how this app should be like.

**Comment by farfromrefug** [comment]
@hammerfunctor thanks and great idea! i created an issue for that
