### ISSUE TITLE
[FEATURE REQUEST] reproducible builds

### ISSUE THREAD

**Issue by e075e** [Akylas/OSS-DocumentScanner#89]
Apks from PlayStore and IzzyOnDroid / github uses a different sign key. So you cannot update one over the other.

**Describe the solution you'd like**
Reproducible builds should solve this

https://f-droid.org/docs/Reproducible_Builds

**Additional context**
Aurora Store screenshot

![Screenshot_Aurora Store](https://github.com/Akylas/OSS-DocumentScanner/assets/15078341/7e42552f-21d1-4cea-9e91-07901677cb00)

**Comment by farfromrefug** [comment]
@e075e It would not solve your issue:
* i dont publish on fdroid and do not plan too out of ecological concerns
* Playstore use its own sign key. It does not use the sign key i use locally

So IzzyOnDroid builds will never have the key as the play store version. Same for 90% of apps today. 
You can still upgrade between IzzyOnDroid and github though

**Comment by blaueente** [comment]
just out out of curiosity: what are your ecological concerns regarding F-Droid?

**Comment by Frmd-git** [comment]
As most users are privacy- and security-oriented, reproducible builds would be a big step forward.
Izzy displays it in bis repository and is very helpful helping to implement it.
Doing this and having the app flagged as RB would be a big benefit.

**Comment by farfromrefug** [comment]
@Frmd-git i plan on doing this at one point. But i need time to implement the PR for Fdroid

**Comment by Frmd-git** [comment]
Cool - I heard that Izzy is quite supportive in getting that done.
