### ISSUE TITLE
[FEATURE REQUEST] parallel crop adjustment

### ISSUE THREAD

**Issue by S-Joao-V** [Akylas/OSS-DocumentScanner#91]
Hello, great app so far, have been using weekly usage in different situations!

In the same view as this issue:
https://github.com/Akylas/OSS-DocumentScanner/issues/81

It would be good to have "parallel" handles to adjust both corners at the same time.
In my experience, if you already have your camera aligned with the page to be scanned, but if the automatic corner detection does not work, the proper crop would be quickly set by adjusting one or more sides of the crop area.

Other camera/scan apps have a similar side handle other than just in the corners.

**Comment by farfromrefug** [comment]
@S-Joao-V do you have an example video or something so that i can see how others do that?

**Comment by S-Joao-V** [comment]
![odrive](https://github.com/Akylas/OSS-DocumentScanner/assets/30469363/4bcce47f-cae9-4b75-94e3-99229d9e5e28)
like this in onedrive, each "handle" moves both corners at the same time, even snapping to the inner borders of a page/table/picture within a page.
Samsung camera, after taking a picture as a scan, allows this too, but without the visual cue, dragging the edge of the crop area moves both corners at the same time.

**Comment by farfromrefug** [comment]
ok I sée now but what if the 2 bottom corners are not at the same y? I mean if the detected document is not rectangular it won't work

**Comment by blaueente** [comment]
at least office lens then assumes a perspective distortion and moves the edge such that it stays parallel on the paper. Quite handy: adjust the corners that are visible in the images to correct for perspective distortion, then then "parallel move" the edges to select the actual crop.

**Comment by farfromrefug** [comment]
@blaueente OK I ll start to think on how to do this best

**Comment by farfromrefug** [comment]
@blaueente it is now implemented
