### ISSUE TITLE
question on requested permissions

### ISSUE THREAD

**Issue by IzzySoft** [Akylas/OSS-DocumentScanner#93]
My scanner just got additional checks added, and promptly sent warnings for today's update:

    ! repo/com.akylas.documentscanner_38.apk declares risky permission(s): android.permission.CAMERA android.permission.READ_MEDIA_IMAGES android.permission.READ_EXTERNAL_STORAGE android.permission.READ_PHONE_STATE

While the first 2 permissions are rather clear (scanning with the camera and importing photos to work on), the remaining two are not:

* `READ_EXTERNAL_STORAGE`: minimum Android version to install/run your app is Android 5, so shouldn't storage be accessed via SAF (Storage Access Framework) instead?
* `READ_PHONE_STATE`: as I doubt you'll read from incoming phone calls, what for is this needed?

Thanks in advance for clarification!

**Comment by farfromrefug** [comment]
@IzzySoft 
* `READ_PHONE_STATE`: indeed i see it in my merged manifest but i have looked and it is not coming from my code. Must be coming from an android aar dependency. Do you know if there is a way to find out which dependency is addig which permissions?
* `READ_EXTERNAL_STORAGE` SAF is a nightmare and i try to avoid it as much as i can. Though i am not sure i need that permission as i use the file picker. I will try without it.

**Comment by IzzySoft** [comment]
> Do you know if there is a way to find out which dependency is addig which permissions?

Except for checking each dependency's `AndroidManifest.xml` you mean? Unfortunately not. An alternative to finding the culprit could be to mute it, like [Removing Unwanted Manifest Permissions With tools:node](https://developermemos.com/posts/removing-unwanted-manifest-permissions/).

> SAF is a nightmare and i try to avoid it as much as i can.

`READ_EXTERNAL_STORAGE` is a nightmare concerning knowing all the exceptions of where it is still needed even if you are using SAF, or don't even explicitly need the storage access. It's the one permission with the most complex set of "2-need-or-not-2-need". SAF is a nightmare when it comes to performance, which luckily only affects "large operations" (e.g. is not noticable if you just want to read/write one or a few files – but gets horrible if you want to sync an entire directory tree). I cannot speak for implementation issues here as I'm not an Android dev – I only know that I will never blame a dev on this one as I totally understand the weirdness.

> i indeed dont need `READ_EXTERNAL_STORAGE`. Just removed it

Yay, nice! Thanks! But before we start the party: does the resulting `AndroidManifest.xml` require `WRITE_EXTERNAL_STORAGE`? Because then `READ_INTERNAL_STORAGE` would be granted implicitly, so you'd need to ensure it's gone by using the above `tools:node` approach (found that hint mentioned in the code comments of some Flutter plugin, where this path was being chosen).

**Comment by farfromrefug** [comment]
@IzzySoft yes i know security wise SAF is better but from a dev point of view just nightmare :D most of us still dont really understand it :D 

Yes my apps ask for `WRITE_EXTERNAL_STORAGE` and this i really think i need to write files on external storage (dont use SAF on pre android 11).
You say that `WRITE_EXTERNAL_STORAGE` enforces `READ_INTERNAL_STORAGE` and thus i need to use `tools:node` to prevent that?

**Comment by IzzySoft** [comment]
Yes. If you declare `WRITE_EXTERNAL_STORAGE`, `READ_INTERNAL_STORAGE` will be granted implicitly. [See here](https://github.com/aosp-mirror/platform_frameworks_base/blob/ec462238f68e4be2baf59b841bc96ba0d2a7fb36/tools/aapt/Command.cpp#L2036) for a reference (and yes, it's not the only "implied" permission, there are 2 more, easily visible in the linked code: `READ_CALL_LOG` when `READ_CONTACTS` is requested and `targetSdkVersion < 16` – plus the same for the corresponding `WRITE_*`).

And yes, according to what I found, `tools:node` should counter that. Though I don't see that reflected in the linked `aapt` code – but maybe the `hasReadExternalStoragePermission` somehow takes it into consideration; I didn't dig into that; could be [this line](https://github.com/aosp-mirror/platform_frameworks_base/blob/ec462238f68e4be2baf59b841bc96ba0d2a7fb36/tools/aapt/Command.cpp#L1557) seeing its declaration, ignoring the `tools:node` attribute for this evaluation.

**Comment by IzzySoft** [comment]
Gah. You'll need `READ_EXTERNAL_STORAGE` to access media directories at least up to Android 9, so better keep it (I've just added it to the allow-list for your app).

Remains the question if you were successful in finding out what brings in `READ_PHONE_STATE`? Was still there in today's release.

**Comment by IzzySoft** [comment]
And in today's release again…

**Comment by farfromrefug** [comment]
@IzzySoft strange this time i used this `<uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" tools:node="remove"/>`

**Comment by IzzySoft** [comment]
Urgs. OK, that's now the second time I hear this. Let me take a closer look… Hm, that's unexpected. From `aapt dump badging`:

```
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.READ_MEDIA_IMAGES'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE' maxSdkVersion='29'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.USE_BIOMETRIC'
uses-permission: name='android.permission.USE_FINGERPRINT'
uses-permission: name='com.akylas.documentscanner.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE' maxSdkVersion='28'
uses-permission: name='android.permission.READ_PHONE_STATE'
```

or by the Manifest (extracted from the APK using `androguard axml`):

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="44" android:versionName="1.4.3.44" android:compileSdkVersion="34" android:compileSdkVersionCodename="14" package="com.akylas.documentscanner" platformBuildVersionCode="34" platformBuildVersionName="14">
  <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="34"/>
  <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true"/>
  <uses-feature android:name="android.hardware.camera" android:required="true"/>
  <uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
  <queries>
    <intent>
      <action android:name="androidx.camera.extensions.action.VENDOR_ACTION"/>
    </intent>
  </queries>
  <uses-permission android:name="android.permission.USE_BIOMETRIC"/>
  <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
  <permission android:name="com.akylas.documentscanner.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" android:protectionLevel="0x00000002"/>
  <uses-permission android:name="com.akylas.documentscanner.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="28"/>
  <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
```

It's indeed there *explicitly* (if it were removed, it might have come back "implicitly").

To keep the fuss small, let me quote myself from above:

> You'll need `READ_EXTERNAL_STORAGE` to access media directories at least up to Android 9, so better keep it (I've just added it to the allow-list for your app).

Let's keep it that way I'd say:

![image](https://github.com/Akylas/OSS-DocumentScanner/assets/6781438/1d636b87-48d5-464c-a8f5-194ec6796483)

and instead have

```xml
<uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove"/>
```

maybe? Oh, and if you wonder about that `DEPENDENCY_INFO_BLOCK`, if you use gradle that's easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by farfromrefug** [comment]
@IzzySoft OK thanks I ll do that. and thanks for dependenciesInfo. I was thinking about removing that for github/fdroid builds!
