### ISSUE TITLE
[FEATURE REQUEST] An option to expand the crop window to cover the whole image

### ISSUE THREAD

**Issue by Umairuem** [Akylas/OSS-DocumentScanner#96]
**Is your feature request related to a problem? Please describe.**
It is time-taking to move all four corners if we want to keep a picture from our gallery as "No Crop".

**Describe the solution you'd like**
An option that allows the crop window to expand to the whole image file.

**Describe alternatives you've considered**
Taking all 4 corners of the crop window to the image corners one by one, which is really time-consuming for multiple images.

**Comment by Umairuem** [comment]
Here's what I want. A single button that would reset the borders even when there's the document. These demonstration screenshots are from Google Lens:

![Picsart_24-01-29_17-30-12-805](https://github.com/Akylas/OSS-DocumentScanner/assets/120035242/1f9f6c0e-4623-4bc3-b009-908563fc35e5)

As for OSS Doc Scanner, I can only reset the borders by bringing every corner to it's position, which takes time and some effort especially when we have to deal with a lot of images. So, such a one-click option would be very helpful.
Here's the OSS Scanner's Screenshot about what we get when I want to convert some images into a PDF:

![Screenshot_20240129-172824](https://github.com/Akylas/OSS-DocumentScanner/assets/120035242/d78e6158-0be5-48e6-a4a0-ae8048ce0a10)

**Comment by farfromrefug** [comment]
@Umairuem OK will look at it. but your screenshot of my app. shows what I said. no document is discovered (because the full camera view is white so no document borders) so the app default to a full image size with a margin . I was proposing to make that margin configurable. that way you could put that to 0 and in your case the crop would be set right away to the full image

**Comment by Umairuem** [comment]
Yes, that could also work as a solution to this!

**Comment by farfromrefug** [comment]
@Umairuem just published a new version with that feature. Let me know if that is what you are looking for

**Comment by Umairuem** [comment]
Yes. That's what I wanted.
THANKS!
