### ISSUE TITLE
[FEATURE REQUEST] Auto-scan

### ISSUE THREAD

**Issue by jvadair** [Akylas/OSS-DocumentScanner#98]
**Is your feature request related to a problem? Please describe.**
I frequently scan large volumes of documents with my phone, typically using vflat. The glue that holds the whole setup together is vflat's auto scan feature. The ability to move a document into the view of the camera, let it scan, and then move on to another document quickly is incredibly useful. In fact, I actually spent several hours hunting online for an older version of vflat when they got rid of the auto scan feature from the free version.

**Describe the solution you'd like**
Essentially, the process should work like this:
- a user moves the document into view of the phone
- the app displays the Border around the phone, and does some sort of animation for a second or so before taking the picture
- the user moves the document away, repeat

Here is an example of what it looks like implemented (vflat):
![Screenshot_2024-01-27-11-51-25-26_930ee7d2985167ff9456b472c4028ebe_1.jpg](https://github.com/Akylas/OSS-DocumentScanner/assets/58600250/246daa54-d34d-4bb8-9fc0-33da02717d98)

**Describe alternatives you've considered**
The batch scan feature is already incredibly useful, and I think this change would probably be fairly easy to implement (though I don't know this tech stack) since the app already detects the document border in real time and displays it on the screen.

**Additional context**
As other comments have mentioned, I'm blown away by the quality of this app, it's not something I was expecting to find in the FOSS world. Thank you, and keep up the good work!

**Comment by farfromrefug** [comment]
@jvadair thanks for the knid words!
I have been wanting to implement that feature from the start. indeed fairly easy just one tricky part I need to figure out: how to determine when you. move too much to break the current "timer". the real time scanning is " moving" quite a bit because of the camera and the lightning. I guess I need to test different parameters to find the right one.
if you have any idea please share!

**Comment by farfromrefug** [comment]
@jvadair just pushed a new version with basic auto scan feature. Let me know how it goes

**Comment by jvadair** [comment]
It seems to work pretty well, though I did have some initial issues trying to get it to work. Honestly not sure what caused these because they seems to be resolved after I reinstalled the app. Additionally, images that are taken together are usually grouped together, correct? Or am I just remembering wrong? Because they are all added as separate documents with the auto scan feature.

**Comment by farfromrefug** [comment]
@jvadair you can enable batch scanning with the button on the of the capture button. 
what were your first issues?

**Comment by jvadair** [comment]
No error messages or traceable issues, but the app would basically only scan 1 page before crashing.

**Comment by farfromrefug** [comment]
oh OK. and it does not happen anymore?

**Comment by jvadair** [comment]
No, it does not.

**Comment by farfromrefug** [comment]
@jvadair can we close this ?

**Comment by jvadair** [comment]
Yes of course, my apologies.

**Comment by farfromrefug** [comment]
@jvadair no need to apology ! glad you had me implement this
