### ISSUE TITLE
[BUG] WebDAV doesn't store password

### ISSUE THREAD

**Issue by OneCreek** [Akylas/OSS-DocumentScanner#99]
### Version

1.3.2 Build 40

### What platform are you using?

Android

### OS Version

Android 14 Stockrom

### What happened?

I set up the WebDAV and testing also works. So I save, but when I open the settings again, the test fails and it says "password was not safed/stored". 
If I reenter the password, the test passes again. 

What's the reason that I always need to reenter the password. Is this on purpose?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OneCreek** [comment]
> @OneCreek it is on purpose that i dont save your password(security reason). That error message comes from your server. What kind of webdav server is it?

Thank you for your fast reply. 

So do I understand this correctly: I need to enter my password each time I want to synchronize?
how can than the sync button on the main screen be interpreted? I press it (for me it is greyed out, but let's say it's funktional) and then I need to enter the password again?

I tried it with [bytemark/webdav](https://github.com/BytemarkHosting/docker-webdav) and [sftpgo](https://github.com/drakkan/sftpgo), which I'm currently using. In different WebDAV clients/explorers it works just fine.

**Comment by OneCreek** [comment]
> Digest for authentication
sorry for the late reply. I stopped using [bytemark/webdav](https://github.com/BytemarkHosting/docker-webdav) because since 6 years no update. But to your question: for all providers I use Basic Auth with Username & Password.

**Comment by OneCreek** [comment]
@farfromrefug anything new/more I can provide/support with this issue?

**Comment by farfromrefug** [comment]
@OneCreek Sorry i actually misread the issue
About the settings and opening it again =>test fail.
 This is normal, and the reason is that i dont want to store your password, instead i store a hash. So when you open the settings again the password field is empty and thus the test will fail. Not sure i want to fix that as i really dont want to store your password.
But all that does not mean you have to re enter your password again. The hash i am talking about is used for all webdav requests. It is just the settings page (used to create the hash) where you need to enter your password again if you want to "test" or "save"

**Comment by OneCreek** [comment]
@farfromrefug makes sense and I agree with the approach not storing the password. But then I still have the issue https://github.com/Akylas/OSS-DocumentScanner/issues/110 happening for me... :(

**Comment by farfromrefug** [comment]
@OneCreek OK re opened it. to be clear. do you get 401 error always with WebDAV? or dors it work sometimes ?

**Comment by OneCreek** [comment]
Should we continue here or the other one?
It worked apparently (test passed and pressing save) but from there on I get the error I guess.

**Comment by farfromrefug** [comment]
@OneCreek let s continue there. will try to reproduce

**Comment by OneCreek** [comment]
I finally got it working! :) But too much changes on my and app side to reproduce I guess...
